import {useEffect,useMemo,useRef,useState} from 'react';
import {Play,Pause,DownloadSimple,SpeakerHigh,Waveform} from '@phosphor-icons/react';
import {Button,Notice,Tabs,Empty} from './ui';
import {canAccess,formatDuration,useApp} from '../data/store';
type Component='original'|'heart'|'lung';
const RATE=8000;
function generate(duration:number){const heart=new Float32Array(Math.floor(duration*RATE)),lung=new Float32Array(heart.length),original=new Float32Array(heart.length);let seed=781,filtered=0;for(let i=0;i<heart.length;i++){const t=i/RATE,phase=t%0.83;heart[i]=Math.sin(2*Math.PI*72*t)*Math.exp(-(((phase-.13)/.045)**2))*.35+Math.sin(2*Math.PI*108*t)*Math.exp(-(((phase-.39)/.025)**2))*.22;seed=(seed*1664525+1013904223)>>>0;filtered=filtered*.7+((seed/4294967296)*2-1)*.3;lung[i]=filtered*(.12+.22*(.5+.5*Math.sin(t*1.4)));original[i]=heart[i]+lung[i];}return {original,heart,lung};}
function wav(samples:Float32Array){const bytes=new ArrayBuffer(44+samples.length*2),v=new DataView(bytes);const text=(offset:number,s:string)=>{for(let i=0;i<s.length;i++)v.setUint8(offset+i,s.charCodeAt(i));};text(0,'RIFF');v.setUint32(4,36+samples.length*2,true);text(8,'WAVE');text(12,'fmt ');v.setUint32(16,16,true);v.setUint16(20,1,true);v.setUint16(22,1,true);v.setUint32(24,RATE,true);v.setUint32(28,RATE*2,true);v.setUint16(32,2,true);v.setUint16(34,16,true);text(36,'data');v.setUint32(40,samples.length*2,true);samples.forEach((x,i)=>v.setInt16(44+i*2,Math.max(-1,Math.min(1,x))*32767,true));return new Blob([bytes],{type:'audio/wav'});}
function SignalCanvas({samples,view,component}:{samples:Float32Array;view:string;component:Component}){const ref=useRef<HTMLCanvasElement>(null);useEffect(()=>{const canvas=ref.current;if(!canvas)return;const draw=()=>{const w=Math.round(canvas.clientWidth),h=90;if(!w)return;const ratio=Math.min(2,devicePixelRatio);canvas.width=w*ratio;canvas.height=h*ratio;const c=canvas.getContext('2d')!;c.scale(ratio,ratio);c.fillStyle='#f5f9fc';c.fillRect(0,0,w,h);if(view==='waveform'){c.strokeStyle='#dce6ee';c.beginPath();for(let y=15;y<h;y+=20){c.moveTo(0,y);c.lineTo(w,y);}c.stroke();c.strokeStyle=component==='heart'?'#668a9b':component==='lung'?'#a08f9e':'#6b819b';c.lineWidth=1;c.beginPath();for(let x=0;x<w;x++){const a=Math.floor(x*samples.length/w),b=Math.floor((x+1)*samples.length/w);let peak=0;for(let i=a;i<b;i++)peak=Math.max(peak,Math.abs(samples[i]));c.moveTo(x,h/2-peak*h*.95);c.lineTo(x,h/2+peak*h*.95);}c.stroke();}else{const cols=Math.min(170,w),bins=42,N=128;for(let x=0;x<cols;x++){const offset=Math.floor(x/cols*(samples.length-N));for(let k=1;k<bins;k++){let re=0,im=0;for(let n=0;n<N;n++){const sample=samples[offset+n]*(.5-.5*Math.cos(2*Math.PI*n/(N-1))),angle=2*Math.PI*k*n/N;re+=sample*Math.cos(angle);im-=sample*Math.sin(angle);}const power=Math.min(1,Math.max(0,(Math.log10(Math.sqrt(re*re+im*im)+.002)+2.2)/2.8));c.fillStyle=`rgb(${Math.round(239-power*121)},${Math.round(246-power*112)},${Math.round(251-power*84)})`;c.fillRect(x*w/cols,h-k*h/bins,Math.ceil(w/cols)+1,Math.ceil(h/bins)+1);}}}};draw();const observer=new ResizeObserver(draw);observer.observe(canvas);return()=>observer.disconnect();},[samples,view,component]);return <canvas ref={ref} aria-label={`${component} synthetic ${view}. Not a patient recording.`} role="img"/>;}
export default function AudioWorkbench({recordingId,resultId,showDownloads=true}:{recordingId:string;resultId?:string;showDownloads?:boolean}){const {state,user,preferences,notify}=useApp();const recording=state.recordings.find(r=>r.id===recordingId);const allowed=canAccess(state,user,recordingId);const duration=Math.min(recording?.duration||20,60);const signals=useMemo(()=>generate(duration),[duration]);const [view,setView]=useState('waveform'),[component,setComponent]=useState<Component>('original'),[playing,setPlaying]=useState(false),[position,setPosition]=useState(0),[volume,setVolume]=useState(.65);const audio=useRef<AudioContext|null>(null),source=useRef<AudioBufferSourceNode|null>(null),gain=useRef<GainNode|null>(null),start=useRef(0),offset=useRef(0),rate=preferences.playbackRate||1;
 function stop(){source.current?.stop();source.current?.disconnect();source.current=null;setPlaying(false);}
 useEffect(()=>()=>{source.current?.stop();audio.current?.close();},[]);
 useEffect(()=>{if(!allowed)stop();},[allowed]);
 useEffect(()=>{if(!playing)return;const timer=setInterval(()=>{const t=offset.current+(audio.current!.currentTime-start.current)*rate;if(t>=duration){stop();setPosition(0);}else setPosition(t);},80);return()=>clearInterval(timer);},[playing,duration,rate]);
 useEffect(()=>{if(gain.current)gain.current.gain.value=volume;},[volume]);
 async function play(kind:Component=component,time=position){try{stop();const context=audio.current||new AudioContext();audio.current=context;await context.resume();const buffer=context.createBuffer(1,signals[kind].length,RATE);buffer.copyToChannel(signals[kind],0);const node=context.createBufferSource();node.buffer=buffer;node.playbackRate.value=rate;const g=context.createGain();g.gain.value=volume;node.connect(g);g.connect(context.destination);gain.current=g;source.current=node;setComponent(kind);offset.current=time>=duration?0:time;start.current=context.currentTime;node.start(0,offset.current);setPlaying(true);}catch{notify('Audio could not start. Check browser playback permissions.');}}
 function download(kind:Component){if(!allowed)return;const url=URL.createObjectURL(wav(signals[kind]));const a=document.createElement('a');a.href=url;a.download=`DEMO-synthetic-${kind}-${recordingId}.wav`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);notify('Downloaded a synthetic demo WAV, not separated patient audio.');}
 if(!allowed)return <Empty title="Audio access is restricted" description="Only the owner or an explicitly authorized recipient may listen to this recording."/>;
 const kinds:Component[]=resultId?['original','heart','lung']:['original'];
 return <section className="audio-workbench" aria-label="Audio comparison"><div className="panel-heading"><div><h2><Waveform size={18} style={{verticalAlign:'middle',marginRight:8}}/>Listen closely</h2><p>Generated synthetic samples · {duration}s · {RATE.toLocaleString()} Hz · mono</p></div></div><Notice>Demonstration audio and visualizations only. These signals are generated locally, not uploaded recordings or actual model outputs.</Notice><Tabs value={view} onChange={setView} items={[{id:'waveform',label:'Waveforms'},{id:'spectrogram',label:'Spectrograms'}]}/><div className="audio-lanes">{kinds.map(kind=><div className="audio-lane" key={kind}><div><strong>{kind==='original'?'Mixed recording':kind==='heart'?'Heart component':'Lung component'}</strong><small>{kind==='original'?'Synthetic mixture':'Synthetic component'}</small><div className="row-actions"><button className="icon-button" aria-label={`${playing&&component===kind?'Pause':'Play'} ${kind}`} onClick={()=>playing&&component===kind?stop():play(kind)}>{playing&&component===kind?<Pause size={19}/>:<Play size={19}/>}</button>{showDownloads&&<button className="icon-button" aria-label={`Download synthetic ${kind} WAV`} onClick={()=>download(kind)}><DownloadSimple size={17}/></button>}</div></div><SignalCanvas samples={signals[kind]} view={view} component={kind}/></div>)}</div><div className="audio-controls"><time>{formatDuration(position)}</time><input type="range" aria-label="Playback position" min="0" max={duration} step="0.1" value={position} onChange={e=>{const t=+e.target.value;setPosition(t);if(playing)void play(component,t);}}/><time>{formatDuration(duration)}</time><SpeakerHigh size={17}/><input style={{maxWidth:75}} aria-label="Volume" type="range" min="0" max="1" step="0.05" value={volume} onChange={e=>setVolume(+e.target.value)}/></div><p className="note-text">{view==='spectrogram'?'Short-time Fourier magnitude of the synthetic signal. Low frequencies at the bottom; time runs left to right.':'Time-aligned sample amplitude; no diagnostic interpretation.'} Playback {rate}×. No automatic audio playback.</p></section>;
}
