import {Children,cloneElement,isValidElement,useId,useEffect,useRef,useState,type ReactElement,type ReactNode,type ButtonHTMLAttributes} from 'react';
import {Link,useBlocker,useLocation} from 'react-router-dom';
import {ArrowRight,Check,Copy,X,WarningCircle} from '@phosphor-icons/react';
import {useApp} from '../data/store';
import {WinterArt} from './WinterArt';
import {ReferenceArt,type ReferenceArtwork} from './ReferenceArt';
export function Button({children,to,variant='primary',className='',...props}:ButtonHTMLAttributes<HTMLButtonElement>&{children:ReactNode;to?:string;variant?:'primary'|'secondary'|'ghost'|'danger'}){const cls=`button button-${variant} ${className}`;return to?<Link className={cls} to={to}>{children}</Link>:<button className={cls} type="button" {...props}>{children}</button>;}
export function PageHeading({eyebrow,title,description,actions}:{eyebrow?:string;title:string;description?:ReactNode;actions?:ReactNode}){
 const {pathname}=useLocation();
 const artByRoute:Record<string,ReferenceArtwork>={'/app/dashboard':'owl','/app/settings':'settingsOwl','/app/review-queue':'owl','/app/history':'owl','/app/shared':'sharedOwl','/app/admin/ensemble':'ensembleOwl','/app/admin/audit':'owl'};
 const art=artByRoute[pathname];
 const quote=pathname==='/app/recordings'?<>Every recording<br/>moves research<br/>forward.</>:pathname==='/app/results'?<>Better tools<br/>for brighter<br/>tomorrows.</>:pathname==='/app/processing'?<>Many recordings.<br/>Deeper<br/>understanding.</>:pathname==='/app/admin/settings'?<>Trusted configuration<br/>for brighter<br/>tomorrows.</>:pathname==='/app/assigned'?<>Small sounds.<br/>Big possibilities.</>:null;
 return <header data-route={pathname} className={`page-heading ${art?'page-heading-owl':''}`}>
  <div className="page-heading-copy">{eyebrow&&<p className="eyebrow">{eyebrow}</p>}<h1>{title}</h1>{description&&<p className="page-description">{description}</p>}</div>
  {art&&<ReferenceArt kind={art} className="page-heading-art"/>}
  {!art&&quote&&<aside className="page-heading-quote" aria-hidden="true">{quote}<span/></aside>}
  {actions&&<div className="page-actions">{actions}</div>}
 </header>;
}
export function Badge({children,tone='neutral'}:{children:ReactNode;tone?:string}){return <span className={`badge badge-${tone}`}>{children}</span>;}
export function Status({value}:{value:string}){const tone=['completed','ready','succeeded','reviewed','active','verified','success'].includes(value)?'success':['failed','disabled','revoked','cancelled'].includes(value)?'danger':['processing','in-review','queued','pending','partial','re-record'].includes(value)?'warning':'neutral';return <Badge tone={tone}>{value.replaceAll('-',' ')}</Badge>;}
export function Notice({children,tone='info',title}:{children:ReactNode;tone?:string;title?:string}){return <div className={`notice notice-${tone}`} role={tone==='danger'?'alert':undefined}><WarningCircle size={19}/><div>{title&&<strong>{title}</strong>}{children}</div></div>;}
export function Empty({title='Nothing here yet',description,action,artKind='collection'}:{title?:string;description:ReactNode;action?:ReactNode;artKind?:'collection'|'dashboardCollection'}){const {pathname}=useLocation();const illustration=artKind==='collection'&&pathname==='/app/recordings'?'recordingCollection':artKind;return <div className="empty-state"><WinterArt kind={illustration} className="empty-illustration"/><h2>{title}</h2><p>{description}</p>{action}</div>;}
export function Field({label,error,hint,children,className=''}:{label:string;error?:string;hint?:string;children:ReactNode;className?:string}){const id=useId();const controls=Children.map(children,child=>{if(isValidElement(child)&&typeof child.type==='string'&&['input','select','textarea'].includes(child.type)){const control=child as ReactElement<Record<string,unknown>>;return cloneElement(control,{'aria-labelledby':`${id}-label`,'aria-describedby':[control.props['aria-describedby'],hint?`${id}-hint`:null,error?`${id}-error`:null].filter(Boolean).join(' ')||undefined,'aria-invalid':error?true:control.props['aria-invalid']});}return child;});return <label className={`field ${className}`}><span id={`${id}-label`}>{label}</span>{controls}{hint&&<small id={`${id}-hint`}>{hint}</small>}{error&&<small id={`${id}-error`} className="field-error" role="alert">{error}</small>}</label>;}
export function Modal({open,onClose,title,children,footer}:{open:boolean;onClose:()=>void;title:string;children:ReactNode;footer?:ReactNode}){const ref=useRef<HTMLDialogElement>(null);const titleId=useId();useEffect(()=>{const d=ref.current;if(!d)return;if(open&&!d.open)d.showModal();else if(!open&&d.open)d.close();},[open]);return <dialog ref={ref} className="modal" onCancel={onClose} onClick={e=>{if(e.target===ref.current)onClose();}} aria-labelledby={titleId}><div className="modal-header"><h2 id={titleId}>{title}</h2><button className="icon-button" aria-label="Close dialog" onClick={onClose}><X size={22}/></button></div><div className="modal-body">{children}</div>{footer&&<div className="modal-footer">{footer}</div>}</dialog>;}
export function Confirm({open,onClose,onConfirm,title,children,danger=false,confirmLabel='Confirm'}:{open:boolean;onClose:()=>void;onConfirm:()=>void;title:string;children:ReactNode;danger?:boolean;confirmLabel?:string}){return <Modal open={open} onClose={onClose} title={title} footer={<><Button variant="secondary" onClick={onClose}>Cancel</Button><Button variant={danger?'danger':'primary'} onClick={()=>{onConfirm();onClose();}}>{confirmLabel}</Button></>}>{children}</Modal>;}
export function Tabs({items,value,onChange}:{items:{id:string;label:string;count?:number}[];value:string;onChange:(id:string)=>void}){return <div className="tabs" role="tablist" aria-label="Section tabs">{items.map((item,i)=><button key={item.id} role="tab" aria-selected={item.id===value} tabIndex={item.id===value?0:-1} onKeyDown={e=>{if(e.key==='ArrowRight'||e.key==='ArrowLeft'){e.preventDefault();const next=(i+(e.key==='ArrowRight'?1:-1)+items.length)%items.length;onChange(items[next].id);(e.currentTarget.parentElement?.children[next] as HTMLElement)?.focus();}}} onClick={()=>onChange(item.id)}>{item.label}{item.count!==undefined&&<span>{item.count}</span>}</button>)}</div>;}
export function Table({headers,children,caption}:{headers:string[];children:ReactNode;caption?:string}){return <div className="table-scroll" role="region" aria-label={caption||'Scrollable data table'} tabIndex={0}><table>{caption&&<caption className="sr-only">{caption}</caption>}<thead><tr>{headers.map(h=><th key={h} scope="col">{h}</th>)}</tr></thead><tbody>{children}</tbody></table></div>;}
export function Panel({title,description,actions,children,className=''}:{title?:string;description?:string;actions?:ReactNode;children:ReactNode;className?:string}){return <section className={`panel ${className}`}>{title&&<div className="panel-heading"><div><h2>{title}</h2>{description&&<p>{description}</p>}</div>{actions}</div>}{children}</section>;}
export function StatStrip({items}:{items:{label:string;value:ReactNode;detail?:string}[]}){return <div className="stat-strip">{items.map(item=><div key={item.label}><span>{item.label}</span><strong>{item.value}</strong>{item.detail&&<small>{item.detail}</small>}</div>)}</div>;}
export function CopyId({value}:{value:string}){const {notify}=useApp();return <button className="copy-id" aria-label={`Copy ${value}`} onClick={async()=>{try{await navigator.clipboard.writeText(value);notify('ID copied.');}catch{notify('Copy unavailable in this browser. Select the ID to copy it.');}}}><code>{value}</code><Copy size={14}/></button>;}
export function Pagination({page,total,pageSize=6,onChange}:{page:number;total:number;pageSize?:number;onChange:(page:number)=>void}){const pages=Math.max(1,Math.ceil(total/pageSize));return <div className="pagination"><span>{total===0?'0 items':`${(page-1)*pageSize+1}–${Math.min(page*pageSize,total)} of ${total}`}</span><div><Button variant="ghost" disabled={page<=1} onClick={()=>onChange(page-1)}>Previous</Button><span>{page} / {pages}</span><Button variant="ghost" disabled={page>=pages} onClick={()=>onChange(page+1)}>Next</Button></div></div>;}
export function ErrorState({message,onRetry}:{message:string;onRetry?:()=>void}){return <Notice tone="danger" title="Something needs attention"><p>{message}</p>{onRetry&&<Button variant="secondary" onClick={onRetry}>Try again</Button>}</Notice>;}
export function Skeleton(){return <div className="skeleton" role="status" aria-label="Loading page"><div/><div/><div/></div>;}
export function InlineLink({to,children}:{to:string;children:ReactNode}){return <Link className="inline-link" to={to}>{children}<ArrowRight size={16}/></Link>;}
export function SaveBar({dirty,onSave,onCancel,label='Save changes'}:{dirty:boolean;onSave:()=>void;onCancel:()=>void;label?:string}){return <div className="save-bar"><span>{dirty?'You have unsaved changes.':<><Check size={16}/> All changes saved</>}</span><div><Button variant="secondary" onClick={onCancel} disabled={!dirty}>Cancel</Button><Button onClick={onSave} disabled={!dirty}>{label}</Button></div></div>;}
export function useError(){const [error,setError]=useState('');const run=(action:()=>void)=>{try{setError('');action();}catch(e){setError(e instanceof Error?e.message:'The action could not be completed.');}};return {error,setError,run};}
export function UnsavedGuard({when}:{when:boolean}){const blocker=useBlocker(({currentLocation,nextLocation})=>when&&(currentLocation.pathname!==nextLocation.pathname));useEffect(()=>{if(!when)return;const leave=(event:BeforeUnloadEvent)=>{event.preventDefault();event.returnValue='';};window.addEventListener('beforeunload',leave);return()=>window.removeEventListener('beforeunload',leave);},[when]);return <Modal open={blocker.state==='blocked'} onClose={()=>blocker.state==='blocked'&&blocker.reset()} title="Leave unsaved changes?" footer={<><Button variant="secondary" onClick={()=>blocker.state==='blocked'&&blocker.reset()}>Stay here</Button><Button variant="danger" onClick={()=>blocker.state==='blocked'&&blocker.proceed()}>Discard and leave</Button></>}><p>Your last saved settings are safe. Changes on this page have not been saved.</p></Modal>;}
