import {chromium} from 'playwright-core';
import assert from 'node:assert/strict';
import {access,mkdir,readFile,writeFile} from 'node:fs/promises';
import path from 'node:path';
const base=process.env.FRONTEND_URL||'http://127.0.0.1:4180';
const output=path.resolve(process.env.EVIDENCE_ROOT||'output/playwright/m1/browser');
try{await access(output);throw new Error('Refusing to overwrite M1 evidence.');}catch(error){if(error.code!=='ENOENT')throw error;}
await mkdir(output,{recursive:true});
const browser=await chromium.launch({executablePath:'/usr/bin/google-chrome',headless:true,args:['--no-sandbox']});
const checks=[],errors=[],requests=[];
const appModule=await readFile(new URL('./mock-firebase-app.mjs',import.meta.url),'utf8');
const authModule=await readFile(new URL('./mock-firebase-auth.mjs',import.meta.url),'utf8');
const state={users:Object.fromEntries(['alice','bob','analyst','admin','google','unverified','newperson'].map(uid=>[uid,{id:`live-${uid}`,uid,email:`${uid}@example.invalid`,display_name:uid,role:uid==='admin'?'admin':uid==='analyst'?'audio_analyst':'healthcare_staff',status:'active',email_verified:true}])),records:[],grants:[],reviews:{},preferences:{},expired:false};
function recording(id,owner){return {id,owner_id:`live-${owner}`,title:`${owner} real mock recording`,original_filename:'research.wav',created_at:1790400000,duration_sec:1,sample_rate_hz:8000,channels:1,file_size_bytes:16044,original_resource_id:`media-${id}`,resources:[{id:`media-${id}`,kind:'original_audio',media_type:'audio/wav',url:`/api/media/media-${id}`}],is_owner:true};}
state.records=[recording('record-a','alice'),recording('record-b','bob')];
function wav(){const b=Buffer.alloc(16044);b.write('RIFF',0);b.writeUInt32LE(b.length-8,4);b.write('WAVEfmt ',8);b.writeUInt32LE(16,16);b.writeUInt16LE(1,20);b.writeUInt16LE(1,22);b.writeUInt32LE(8000,24);b.writeUInt32LE(16000,28);b.writeUInt16LE(2,32);b.writeUInt16LE(16,34);b.write('data',36);b.writeUInt32LE(16000,40);return b;}
async function context(mock=false,viewport={width:1536,height:1024}){
 const context=await browser.newContext({viewport,reducedMotion:'reduce'});
 context.on('page',page=>page.on('pageerror',error=>errors.push(error.message)));
 if(mock){
  await context.route('**/node_modules/.vite/deps/firebase_app.js*',route=>route.fulfill({contentType:'application/javascript',body:appModule}));
  await context.route('**/node_modules/.vite/deps/firebase_auth.js*',route=>route.fulfill({contentType:'application/javascript',body:authModule}));
  await context.route('**/src/config/runtime.ts*',route=>route.fulfill({contentType:'application/javascript',body:"export const FIREBASE_PROJECT='stethofuse-c18cd-3cca0';export const PUBLIC_ORIGIN='https://stethofuse.ashraf-alsaloul.com';export const DEMO_ENABLED=false;export const firebaseConfigurationError='';export const firebaseConfiguration=()=>({projectId:FIREBASE_PROJECT,apiKey:'TEST-ONLY-NETWORK-MOCK',authDomain:FIREBASE_PROJECT+'.firebaseapp.com',appId:'TEST-ONLY'});"}));
  await context.route('**/api/**',async route=>{
   const request=route.request(),url=new URL(request.url()),p=url.pathname.replace('/api',''),method=request.method();
   const authorization=request.headers().authorization||'',uid=authorization.replace('Bearer M1-MOCK:',''),user=state.users[uid];
   requests.push({path:p,method,bearerPresent:authorization.startsWith('Bearer M1-MOCK:'),query:url.search,bodyFields:request.headers()['content-type']?.includes('application/json')?Object.keys(request.postDataJSON()||{}):[]});
   const respond=(data,status=200)=>route.fulfill({status,contentType:'application/json',body:JSON.stringify(data)});
   const fail=(code,status)=>respond({detail:{code,message:'Safe mock error.'}},status);
   if(!user||state.expired)return fail('invalid_token',401);
   const body=request.headers()['content-type']?.includes('application/json')?request.postDataJSON():null;
   if(user.status!=='active')return fail('account_disabled',403);
   const session=()=>({user,mode:'live',capabilities:{recordings:true,sharing:true,reviews:user.role==='audio_analyst',admin:user.role==='admin',ensemble:false}});
   if(p==='/auth/session'||p==='/auth/me'){
    if(method==='PATCH')user.display_name=body.display_name;
    return respond(session());
   }
   if(p==='/preferences'){if(method==='PATCH'){assert(body.preferences);state.preferences[user.id]={...state.preferences[user.id],...body.preferences};}return respond({preferences:state.preferences[user.id]||{}});}
   const allowed=r=>r.owner_id===user.id||state.grants.some(g=>g.recording_id===r.id&&g.recipient_id===user.id&&g.status==='active');
   if(p==='/recordings'){
    if(method==='POST'){assert.match(request.headers()['content-type'],/multipart\/form-data/);const r=recording('uploaded-a',uid);r.title='Uploaded server record';state.records.push(r);return respond(r,201);}
    return respond({items:state.records.filter(allowed).map(r=>({...r,is_owner:r.owner_id===user.id}))});
   }
   if(/^\/recordings\/[^/]+\/grants$/.test(p)){
    const r=state.records.find(r=>r.id===p.split('/')[2]);if(!r||r.owner_id!==user.id)return fail('forbidden',403);
    if(method==='POST'){if(body.permission==='review'&&state.users[body.recipient_id.replace('live-','')]?.role!=='audio_analyst')return fail('forbidden',403);const grant={id:`grant-${state.grants.length+1}`,recording_id:r.id,resource_id:body.resource_id||null,grantor_id:user.id,recipient_id:body.recipient_id,permission:body.permission,status:'active',created_at:1790400000,expires_at:null,revoked_at:null};state.grants.push(grant);return respond(grant,201);}
    return respond({items:state.grants.filter(g=>g.recording_id===r.id)});
   }
   if(/^\/recordings\/[^/]+\/revoke-access$/.test(p)){let revoked=0;for(const g of state.grants)if(g.recording_id===body.confirmed_recording_id&&g.recipient_id===body.recipient_id&&g.grantor_id===user.id){g.status='revoked';revoked++;}return respond({revoked});}
   if(/^\/grants\/[^/]+$/.test(p)){const g=state.grants.find(g=>g.id===p.split('/')[2]);if(!g||g.grantor_id!==user.id)return fail('forbidden',403);g.status='revoked';return route.fulfill({status:204});}
   if(/^\/recordings\/[^/]+$/.test(p)){const r=state.records.find(r=>r.id===p.split('/')[2]);if(!r||!allowed(r))return fail('forbidden',403);if(method==='PATCH'){if(r.owner_id!==user.id)return fail('forbidden',403);r.title=body.title;}return respond({...r,is_owner:r.owner_id===user.id});}
   if(p==='/jobs'||p==='/results')return respond({items:[]});
   if(p.startsWith('/media/')){const r=state.records.find(r=>r.original_resource_id===p.split('/')[2]);if(!r||!allowed(r))return fail('forbidden',403);return route.fulfill({contentType:'audio/wav',body:wav()});}
   if(p==='/assignments')return respond({items:state.grants.filter(g=>g.permission==='review'&&g.status==='active'&&g.recipient_id===user.id)});
   if(/^\/assignments\/[^/]+\/review$/.test(p)){const id=p.split('/')[2],g=state.grants.find(g=>g.id===id&&g.status==='active'&&g.recipient_id===user.id&&g.permission==='review');if(!g||user.role!=='audio_analyst')return fail('forbidden',403);const initial={assignment_id:id,resource_id:g.resource_id,reviewer_id:user.id,decision:'pending',notes:'',updated_at:null};if(method==='PUT')state.reviews[id]={...initial,...body,updated_at:1790400050};return respond(state.reviews[id]||initial);}
   if(p.startsWith('/admin/')){if(user.role!=='admin')return fail('forbidden',403);if(p==='/admin/users')return respond({items:Object.values(state.users)});if(p==='/admin/audit')return respond({items:[]});if(method==='PATCH'){const target=Object.values(state.users).find(u=>u.id===p.split('/')[3]);if(!target||body.confirmed_target_id!==target.id)return fail('forbidden',403);if(target.role==='admin'&&body.role!=='admin')return fail('last_admin',409);Object.assign(target,{role:body.role,status:body.status});return respond(target);}}
   return fail('not_found',404);
  });
 }
 await context.route(url=>['http:','https:'].includes(url.protocol)&&url.origin!==new URL(base).origin,route=>{errors.push('Unexpected external request blocked.');return route.abort();});
 return context;
}
async function check(name,action){try{await action();checks.push({name,status:'PASS'});console.log('PASS',name);}catch(error){const pages=browser.contexts().flatMap(c=>c.pages());const page=pages.at(-1);const screenshot=`failure-${checks.length+1}.png`;if(page)await page.screenshot({path:path.join(output,screenshot),fullPage:true}).catch(()=>{});checks.push({name,status:'FAIL',error:error.stack,url:page?.url().replace(/\?.*$/,'?redacted'),screenshot});process.exitCode=1;console.error('FAIL',name,error.message);}}
async function go(page,path){await page.goto(base+path);await page.locator('h1').first().waitFor();}
async function signIn(page,uid='alice'){await go(page,'/login');await page.getByRole('textbox',{name:'Email address',exact:true}).fill(`${uid}@example.invalid`);await page.getByLabel('Password',{exact:true}).fill('Test-only-password-26');await page.getByRole('button',{name:'Sign in',exact:true}).click();await page.locator('[data-live-workspace=true]').waitFor();}
try{
 await check('Actual missing-config live build is fail-closed and ignores fixture storage',async()=>{const c=await context(),p=await c.newPage();await c.addInitScript(()=>{sessionStorage.setItem('stethofuse-demo-persona','USR-3001');localStorage.setItem('stethofuse-demo-v1',JSON.stringify({users:[{id:'USR-3001',role:'admin'}]}));});await go(p,'/login');assert(await p.getByText('Authentication setup required',{exact:true}).isVisible());assert(await p.getByRole('button',{name:'Sign in',exact:true}).isDisabled());assert.equal(await p.locator('.demo-entry').count(),0);await p.screenshot({path:path.join(output,'missing-config-login-1536.png')});await go(p,'/app/admin');assert.match(await p.locator('h1').innerText(),/Workspace unavailable/);assert.equal(await p.locator('.app-shell').count(),0);await go(p,'/');await p.locator('#welcome-title').waitFor();assert(await p.locator('.owl-art img').evaluate(e=>e.complete&&e.naturalWidth>0));await c.close();});
 const c=await context(true),p=await c.newPage();
 await check('MOCK SDK email login + bearer session sync and refresh restoration',async()=>{await signIn(p);assert.match(await p.locator('h1').innerText(),/alice/);await p.reload();await p.locator('[data-live-workspace=true]').waitFor();assert.equal(await p.locator('.demo-banner,.demo-entry').count(),0);assert.equal(await p.getByText('Morning chest recording',{exact:true}).count(),0);assert(requests.some(r=>r.path==='/auth/session'&&r.method==='POST'&&r.bearerPresent));await p.screenshot({path:path.join(output,'mock-live-dashboard-1536.png'),fullPage:true});});
 await check('MOCK API owned collections, denied foreign record and no synthetic results',async()=>{await go(p,'/app/recordings');await p.getByText('alice real mock recording',{exact:true}).waitFor();assert.equal(await p.getByText('bob real mock recording',{exact:true}).count(),0);await go(p,'/app/recordings/record-b');await p.getByText('You do not have permission for this action or resource.',{exact:true}).waitFor();assert.equal(await p.locator('audio').count(),0);await go(p,'/app/results');await p.getByRole('heading',{name:'No saved results'}).waitFor();assert.equal(await p.locator('audio,canvas').count(),0);});
 await check('MOCK async upload waits for a server recording ID, then authenticated media blob',async()=>{await go(p,'/app/recordings/new/upload');await p.locator('input[type=file]').setInputFiles({name:'non-sensitive.wav',mimeType:'audio/wav',buffer:wav()});await p.getByLabel('Recording title',{exact:true}).fill('Server title');await p.getByRole('button',{name:'Upload recording',exact:true}).click();await p.waitForURL('**/app/recordings/uploaded-a');await p.getByRole('button',{name:'Load authorized file'}).click();await p.locator('audio').waitFor();assert.match(await p.locator('audio').getAttribute('src'),/^blob:/);assert(await p.getByRole('button',{name:'Separate',exact:true}).isDisabled());});
 await check('MOCK explicit original-resource review grant is awaited and server-returned',async()=>{await go(p,'/app/recordings/record-a');await p.getByLabel('Recipient application ID',{exact:true}).fill('live-analyst');await p.getByLabel('Permission',{exact:true}).selectOption('review');await p.getByLabel('Resource scope',{exact:true}).selectOption('media-record-a');await p.getByRole('button',{name:'Grant access',exact:true}).click();await p.getByRole('button',{name:'Revoke grant',exact:true}).waitFor();assert.equal(state.grants[0].resource_id,'media-record-a');});
 await check('MOCK preferences envelope, profile persistence and mobile containment',async()=>{await go(p,'/app/settings?section=appearance');await p.getByRole('checkbox',{name:'Reduced motion',exact:true}).click();await p.getByText('Preferences saved by the server.',{exact:true}).waitFor();assert.equal(state.preferences['live-alice'].appearance.reducedMotion,true);await go(p,'/app/profile');await p.getByLabel('Display name',{exact:true}).fill('Alice Research');await p.getByRole('button',{name:'Save changes',exact:true}).click();await p.getByText('Profile saved.',{exact:true}).waitFor();assert.equal(state.users.alice.display_name,'Alice Research');await p.setViewportSize({width:390,height:844});await go(p,'/app/dashboard');await p.locator('[data-live-workspace=true]').waitFor();assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await p.screenshot({path:path.join(output,'mock-live-dashboard-390.png'),fullPage:true});await p.setViewportSize({width:1536,height:1024});});
 await check('MOCK logout clears live presentation and no app credentials/tokens are stored',async()=>{await p.getByRole('button',{name:/Alice Research/}).click();await p.getByRole('menuitem',{name:'Sign out',exact:true}).click();await p.waitForURL(url=>url.pathname==='/login');assert.equal(await p.locator('.app-shell').count(),0);const storage=await p.evaluate(()=>({local:{...localStorage},session:{...sessionStorage}}));assert(!JSON.stringify(storage).includes('Test-only-password'));assert(!JSON.stringify(storage).includes('M1-MOCK:'));assert(!('__m1_test_identity'in storage.session));});
 await check('MOCK analyst review saves exact assignment and revocation denies subsequent access',async()=>{await signIn(p,'analyst');await go(p,'/app/reviews/grant-1');await p.getByLabel('Non-diagnostic notes',{exact:true}).fill('Mock review: non-diagnostic research note.');await p.getByLabel('Review decision',{exact:true}).selectOption('accepted');await p.getByRole('button',{name:'Save review',exact:true}).click();await p.getByText('Review saved by the server.',{exact:true}).waitFor();assert.equal(state.reviews['grant-1'].reviewer_id,'live-analyst');state.grants[0].status='revoked';await p.reload();await p.getByText('You do not have permission for this action or resource.',{exact:true}).waitFor();assert.equal(await p.locator('textarea,audio').count(),0);});
 await check('MOCK staff route denial and server role refresh',async()=>{state.users.analyst.role='healthcare_staff';await p.evaluate(()=>window.dispatchEvent(new Event('focus')));await p.waitForURL('**/403');await go(p,'/app/admin/users');await p.waitForURL('**/403');});
 await check('MOCK 401 refresh attempt ends in expired session without stale data',async()=>{state.expired=true;await go(p,'/app/recordings');await p.waitForURL('**/session-expired?**');assert.equal(await p.locator('.app-shell,audio').count(),0);const calls=await p.evaluate(()=>window.__m1SdkCalls);assert(calls.some(x=>x.method==='token.force'));state.expired=false;});
 await c.close();
 const authContext=await context(true),authPage=await authContext.newPage();
 await check('MOCK official Google popup adapter and explicit logout',async()=>{await go(authPage,'/login');await authPage.getByRole('button',{name:'Continue with Google',exact:true}).click();await authPage.locator('[data-live-workspace=true]').waitFor();assert((await authPage.evaluate(()=>window.__m1SdkCalls)).some(x=>x.method==='signInWithPopup'));await authPage.getByRole('button',{name:/google/}).click();await authPage.getByRole('menuitem',{name:'Sign out',exact:true}).click();await authPage.waitForURL(url=>url.pathname==='/login');});
 await check('MOCK registration remains unverified until explicit verification and reload',async()=>{await go(authPage,'/register');await authPage.getByLabel('Full name',{exact:true}).fill('New Researcher');await authPage.getByRole('textbox',{name:'Email address',exact:true}).fill('newperson@example.invalid');await authPage.getByLabel('Password',{exact:true}).fill('Test-only-password-26');await authPage.getByLabel('Confirm password',{exact:true}).fill('Test-only-password-26');await authPage.locator('input[type=checkbox]').check();assert.equal(await authPage.locator('select').count(),0);await authPage.getByRole('button',{name:'Create account',exact:true}).click();await authPage.waitForURL('**/verify-email');await authPage.getByRole('button',{name:'Send verification email',exact:true}).click();await authPage.getByText('Firebase accepted the verification email request. Check your inbox and spam folder.',{exact:true}).waitFor();await authPage.evaluate(()=>window.__m1Verified=true);await authPage.getByRole('button',{name:'I have verified my email',exact:true}).click();await authPage.locator('[data-live-workspace=true]').waitFor();assert.equal(state.users.newperson.role,'healthcare_staff');});
 await check('MOCK reset request and action code is consumed once, cleared from URL and not persisted',async()=>{await go(authPage,'/forgot-password');await authPage.getByLabel('Email address',{exact:true}).fill('newperson@example.invalid');await authPage.getByRole('button',{name:'Request reset link',exact:true}).click();await authPage.getByText(/provider accepted the recovery request/).waitFor();await go(authPage,'/auth/action?mode=resetPassword&oobCode=mock-reset&continueUrl=https%3A%2F%2Fevil.invalid');await authPage.getByLabel('New password',{exact:true}).waitFor();assert.equal(new URL(authPage.url()).search,'');await authPage.getByLabel('New password',{exact:true}).fill('Replacement-mock-password-26');await authPage.getByLabel('Confirm new password',{exact:true}).fill('Replacement-mock-password-26');await authPage.getByRole('button',{name:'Reset password',exact:true}).click();await authPage.getByRole('heading',{name:'Your password has been reset.'}).waitFor();const calls=await authPage.evaluate(()=>window.__m1SdkCalls);assert.equal(calls.filter(x=>x.method==='verifyPasswordResetCode').length,1);assert.equal(calls.filter(x=>x.method==='confirmPasswordReset').length,1);assert(!JSON.stringify(await authPage.evaluate(()=>({...sessionStorage,...localStorage}))).includes('mock-reset'));await go(authPage,'/reset-password?oobCode=expired');await authPage.getByRole('heading',{name:'This link cannot be used.'}).waitFor();assert.equal(new URL(authPage.url()).search,'');});
 await authContext.close();
 await check('No runtime errors, external provider requests, query tokens or submitted ownership/role fields',async()=>{assert.deepEqual(errors,[]);assert(requests.every(r=>r.query===''&&r.bearerPresent));assert(requests.filter(r=>r.path==='/auth/session').every(r=>r.bodyFields.length===0));});
}finally{await writeFile(path.join(output,'results.json'),JSON.stringify({testedAt:new Date().toISOString(),browser:await browser.version(),scope:'Actual missing-config UI plus network-substituted MOCK official Firebase SDK modules and MOCK API. Not emulator, real Firebase, local backend or production verification.',checks,errors,requests},null,2));await browser.close();}
