import assert from 'node:assert/strict';
import {readFile,mkdir,access,writeFile} from 'node:fs/promises';
import {stripTypeScriptTypes} from 'node:module';
import path from 'node:path';
const source=stripTypeScriptTypes(await readFile(new URL('../../src/data/api.ts',import.meta.url),'utf8'),{mode:'transform'});
const {createApiClient,ApiError}=await import('data:text/javascript;base64,'+Buffer.from(source).toString('base64'));
const output=path.resolve(process.env.EVIDENCE_ROOT||'output/playwright/m1/client');
try{await access(output);throw new Error('Refusing to overwrite evidence.');}catch(error){if(error.code!=='ENOENT')throw error;}
await mkdir(output,{recursive:true});
const checks=[];
async function check(name,run){try{await run();checks.push({name,status:'PASS'});console.log('PASS',name);}catch(error){checks.push({name,status:'FAIL',error:error.stack});process.exitCode=1;}}
const response=(status,body={})=>new Response(JSON.stringify(body),{status,headers:{'Content-Type':'application/json'}});
await check('Bearer-only fixed same-origin API: no cookies, cache, redirects or referrer',async()=>{const calls=[];const api=createApiClient(async()=> 'fictional-memory-token',()=>{},async(url,init)=>{calls.push({url,init});return response(200,{items:[]});});assert.deepEqual(await api.json('/recordings'),{items:[]});const {url,init}=calls[0];assert.equal(url,'/api/recordings');assert.equal(init.headers.get('Authorization'),'Bearer fictional-memory-token');assert.equal(init.credentials,'omit');assert.equal(init.cache,'no-store');assert.equal(init.redirect,'error');assert.equal(init.referrerPolicy,'no-referrer');});
await check('Absolute, protocol-relative, traversal, query and encoded paths rejected before token lookup',async()=>{let calls=0;const api=createApiClient(async()=>{calls++;return 'unused';},()=>{});for(const p of ['https://evil.invalid/x','//evil.invalid','/../x','/media/id?token=bad','/media/%2e%2e','/media/id#fragment'])await assert.rejects(api.json(p),/Invalid API path/);assert.equal(calls,0);});
await check('Owner feedback and saved history use bounded numeric pages; raw URLs/tokens remain rejected',async()=>{const calls=[];let tokens=0;const api=createApiClient(async()=>{tokens++;return 'fictional';},()=>{},async(url)=>{calls.push(url);return response(200,{items:[],total:0});});await api.json('/recordings/record-id/reviews',{}, {limit:3,offset:3});await api.json('/reviews/history',{}, {limit:3,offset:6});assert.deepEqual(calls,['/api/recordings/record-id/reviews?limit=3&offset=3','/api/reviews/history?limit=3&offset=6']);for(const page of [{limit:0},{limit:21},{limit:'3&token=bad'},{limit:3,offset:-1},{limit:3,offset:1.5},{limit:NaN}])for(const route of ['/recordings/record-id/reviews','/reviews/history'])await assert.rejects(api.json(route,{},page),/Invalid feedback page/);await assert.rejects(api.json('/media/id',{}, {limit:3}),/Invalid feedback page/);assert.equal(tokens,2);});
await check('One SDK force-refresh retry on 401 then clear session, redact backend details',async()=>{const forces=[];let expired=0,count=0;const api=createApiClient(async force=>{forces.push(force);return 'fictional';},()=>expired++,async()=>{count++;return response(401,{detail:{code:'invalid_token',message:'TOKEN_SECRET'}});});await assert.rejects(api.json('/recordings'),e=>e instanceof ApiError&&e.status===401&&!e.message.includes('TOKEN_SECRET'));assert.deepEqual(forces,[false,true]);assert.equal(count,2);assert.equal(expired,1);});
await check('Recovered 401 retry returns actual response without expiring',async()=>{let count=0,expired=0;const api=createApiClient(async()=> 'fictional',()=>expired++,async()=>++count===1?response(401):response(200,{id:'server-id'}));assert.deepEqual(await api.json('/recordings/server-id'),{id:'server-id'});assert.equal(expired,0);});
await check('403/422/503 details are sanitized without privilege fallbacks',async()=>{for(const status of [403,422,503]){const api=createApiClient(async()=> 'fictional',()=>{},async()=>response(status,{detail:{code:'private_unknown',message:'DATABASE_SECRET'}}));await assert.rejects(api.json('/recordings'),e=>e.status===status&&!e.message.includes('DATABASE_SECRET'));}});
await check('Protected media accepts safe blob MIME, rejects HTML/SVG; no public URL path',async()=>{for(const type of ['text/html','image/svg+xml']){const api=createApiClient(async()=> 'fictional',()=>{},async()=>new Response('unsafe',{headers:{'Content-Type':type}}));await assert.rejects(api.media('resource-id'),/Unsupported protected media type/);}const api=createApiClient(async()=> 'fictional',()=>{},async()=>new Response('wav',{headers:{'Content-Type':'audio/wav'}}));assert.equal((await api.media('resource-id')).type,'audio/wav');});
await check('Account change abort does not expire the replacement account',async()=>{let expired=0;const api=createApiClient(async()=>{throw new DOMException('Account changed.','AbortError');},()=>expired++);await assert.rejects(api.json('/recordings'),e=>e.name==='AbortError');assert.equal(expired,0);});
await writeFile(path.join(output,'results.json'),JSON.stringify({scope:'Unit tests of actual TypeScript API client with MOCK token source and transport; no provider or backend requests.',checks,testedAt:new Date().toISOString()},null,2));
