import {FolderSimple,GearSix,House,List,MagnifyingGlass,Moon,Question,ShareNetwork,ShieldCheck,SignOut,Sun,ClipboardText} from '@phosphor-icons/react';
import {useEffect,useState,type ReactNode} from 'react';
import {Link,NavLink,useLocation,useNavigate} from 'react-router-dom';
import {useLive} from '../data/live';
import {useApp} from '../data/store';
import {liveRoleLabel} from '../data/liveTypes';
import {Button,Modal} from './primitives';
import {FrostPreferences,useFrostPreferences} from './preferences';
import './frost.css';

function ShellContent({children}:{children:ReactNode}){
  const {session,logout,preferences}=useLive(),{toast,notify}=useApp();
  const {resolved,setTheme}=useFrostPreferences(),location=useLocation(),navigate=useNavigate();
  const [drawer,setDrawer]=useState(false);const user=session!.user;
  const label=location.pathname.startsWith('/app/recordings/new')?'New recording':location.pathname.startsWith('/app/recordings/')||location.pathname.startsWith('/app/results/')||location.pathname.startsWith('/app/audio/')?'Recording':location.pathname==='/app/library'?'Library':location.pathname==='/app/overview'?'Overview':location.pathname.startsWith('/app/settings')||location.pathname==='/app/profile'?'Profile & settings':location.pathname.includes('/admin')?'Administration':location.pathname.includes('/help')?'Help':'Shared & assigned';
  function search(){navigate('/app/library');requestAnimationFrame(()=>requestAnimationFrame(()=>document.querySelector<HTMLInputElement>('#library-search')?.focus()));}
  useEffect(()=>{setDrawer(false);window.scrollTo(0,0);document.getElementById('sf-main')?.focus({preventScroll:true});document.title=`StethoFuse · ${label}`;},[location.pathname,label]);
  useEffect(()=>{const key=(e:KeyboardEvent)=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='k'){e.preventDefault();search();}};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key);},[navigate]);
  const links=<><NavLink to="/app/overview"><House size={21}/>Overview</NavLink><NavLink to="/app/library"><FolderSimple size={21}/>Library</NavLink><NavLink to="/app/shared"><ShareNetwork size={21}/>Shared & assigned</NavLink>{user.role==='audio_analyst'&&<NavLink to="/app/review-queue"><ClipboardText size={21}/>Review queue</NavLink>}{user.role==='admin'&&<><NavLink to="/app/admin" end><ShieldCheck size={21}/>Administration</NavLink><NavLink to="/app/admin/users">Users</NavLink><NavLink to="/app/admin/audit">Audit log</NavLink></>}</>;
  return <div className={`sf-app sf-live ${preferences.appearance?.reducedMotion?'reduce-motion':''}`} data-theme={resolved}>
    <a href="#sf-main" className="sf-skip" onClick={e=>{e.preventDefault();document.getElementById('sf-main')?.focus();}}>Skip to content</a>
    <aside className="sf-sidebar"><Link to="/app/overview" className="sf-logo" aria-label="StethoFuse Overview"><img src="/assets/logo.svg" width={185} height={49} alt="StethoFuse"/></Link><div className="sf-workspace-label">Personal workspace</div><nav aria-label="Main navigation">{links}</nav><div className="sf-sidebar-bottom"><div className="sf-private-note"><ShieldCheck size={22}/><span>Private workspace</span></div><nav aria-label="Personal navigation"><NavLink to="/app/settings"><GearSix size={21}/>Profile & settings</NavLink><NavLink to="/app/help"><Question size={21}/>Help</NavLink></nav><Link to="/app/profile" className="sf-sidebar-account"><div className="sf-identity sf-identity--compact"><span className="sf-avatar">{(user.display_name||'Account').split(' ').map(n=>n[0]).slice(0,2).join('')}</span><span><strong>{user.display_name||'Your account'}</strong><small>{user.handle?`@${user.handle}`:liveRoleLabel(user.role)}</small></span></div></Link><button className="sf-signout" onClick={async()=>{try{await logout();navigate('/login');}catch{notify('Sign-out could not be completed. Please retry.');}}}><SignOut size={18}/>Sign out</button></div></aside>
    <div className="sf-main-column"><header className="sf-topbar"><Button variant="icon" className="sf-mobile-menu" aria-label="Open navigation" onClick={()=>setDrawer(true)}><List size={23}/></Button><div className="sf-location"><Link to="/app/overview">Workspace</Link><span>/</span><strong>{label}</strong></div><div className="sf-topbar-actions"><Button variant="ghost" className="sf-search-shortcut" onClick={search}><MagnifyingGlass size={18}/><span>Find a recording</span><kbd>⌘ K</kbd></Button><Button variant="icon" aria-label={resolved==='midnight'?'Switch to Frost theme':'Switch to Midnight theme'} onClick={()=>setTheme(resolved==='midnight'?'frost':'midnight')}>{resolved==='midnight'?<Sun size={20}/>:<Moon size={20}/>}</Button><Link to="/app/profile" className="sf-header-avatar" aria-label="Open your profile">{(user.display_name||'Account')[0]}</Link></div></header>
    <main className="sf-main" id="sf-main" tabIndex={-1} data-live-workspace="true">{children}<footer className="sf-live-footer">Sound separation and technical review. Not a diagnostic tool.</footer></main></div>
    <nav className="sf-mobile-nav" aria-label="Mobile navigation"><NavLink to="/app/overview"><House size={21}/>Overview</NavLink><NavLink to="/app/library"><FolderSimple size={21}/>Library</NavLink><NavLink to="/app/profile"><GearSix size={21}/>Profile</NavLink><Button variant="ghost" onClick={()=>setDrawer(true)}><List size={21}/>More</Button></nav>
    {drawer&&<Modal title="Your workspace" onClose={()=>setDrawer(false)} className="sf-navigation-dialog"><nav>{links}<Link to="/app/profile">Your profile</Link><Link to="/app/settings">Settings</Link><Link to="/app/help">Help</Link><Button variant="ghost" onClick={async()=>{try{await logout();navigate('/login');}catch{notify('Sign-out could not be completed. Please retry.');}}}>Sign out</Button></nav></Modal>}
    {toast&&<div className="sf-toast" role="status">{toast}</div>}
  </div>;
}
export default function FrostShell({children}:{children:ReactNode}){const {session}=useLive();return <FrostPreferences key={session!.user.uid} uid={session!.user.uid}><ShellContent>{children}</ShellContent></FrostPreferences>;}
