ALTER TABLE af_users ADD COLUMN public_id TEXT;
ALTER TABLE af_users ADD COLUMN handle TEXT COLLATE NOCASE;
ALTER TABLE af_users ADD COLUMN normalized_handle TEXT;
ALTER TABLE af_users ADD COLUMN handle_change_count INTEGER NOT NULL DEFAULT 0 CHECK(handle_change_count IN (0,1));
ALTER TABLE af_users ADD COLUMN handle_changed_at INTEGER;
CREATE UNIQUE INDEX af_user_public_id ON af_users(public_id);
CREATE UNIQUE INDEX af_user_handle ON af_users(handle COLLATE NOCASE);
CREATE UNIQUE INDEX af_user_normalized_handle ON af_users(normalized_handle);
ALTER TABLE af_recordings ADD COLUMN public_id TEXT;
CREATE UNIQUE INDEX af_recording_public_id ON af_recordings(public_id);
ALTER TABLE af_resources ADD COLUMN public_id TEXT;
CREATE UNIQUE INDEX af_resource_public_id ON af_resources(public_id);
ALTER TABLE af_grants ADD COLUMN public_id TEXT;
ALTER TABLE af_grants ADD COLUMN assignment_public_id TEXT;
CREATE UNIQUE INDEX af_grant_public_id ON af_grants(public_id);
CREATE UNIQUE INDEX af_assignment_public_id ON af_grants(assignment_public_id);
ALTER TABLE m1_jobs ADD COLUMN public_id TEXT;
CREATE UNIQUE INDEX m1_job_public_id ON m1_jobs(public_id);
ALTER TABLE m1_results ADD COLUMN public_id TEXT;
CREATE UNIQUE INDEX m1_result_public_id ON m1_results(public_id);
DROP TABLE m1_meta;
CREATE TABLE m1_meta (version INTEGER PRIMARY KEY CHECK(version=3));
INSERT INTO m1_meta VALUES(3);
