import {chromium} from 'playwright-core';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import path from 'node:path';
const base=process.env.FRONTEND_URL||'http://127.0.0.1:4180';
const out=path.resolve(process.env.EVIDENCE_ROOT || 'evidence','shared');await fs.mkdir(out,{recursive:true});
const browser=await chromium.launch({executablePath:'/usr/bin/google-chrome',headless:true,args:['--no-sandbox']});
const context=await browser.newContext({viewport:{width:1440,height:1000}});
await context.addInitScript(()=>{window.__storageEvents=0;window.addEventListener('storage',()=>window.__storageEvents++);});
const a=await context.newPage();const failures=[];const results=[];const pages=[a];
const watch=p=>p.on('pageerror',e=>failures.push(e.message));watch(a);
const go=async(p,route)=>{await p.goto(base+route);await p.locator('.workspace h1').waitFor();};
const login=async(p,name)=>{await p.goto(base+'/login#demo-personas');await p.getByRole('button',{name:new RegExp(name)}).click();await p.locator('.app-shell').waitFor();};
const state=p=>p.evaluate(()=>JSON.parse(localStorage.getItem('stethofuse-demo-v1')));
const saved=async p=>{await p.getByRole('button',{name:'Save changes',exact:true}).click();await p.getByText('All changes saved',{exact:true}).waitFor();};
async function check(name,fn){try{await fn();results.push({name,status:'PASS'});console.log('PASS',name);}catch(e){results.push({name,status:'FAIL',error:e.message});await a.screenshot({path:path.join(out,'failure.png'),fullPage:true});throw e;}}
try{
 await login(a,'Amina Rahman');
 await check('Stored preferences migrate missing fields without dropping values',async()=>{
  await a.evaluate(()=>{const s=JSON.parse(localStorage.getItem('stethofuse-demo-v1'));s.preferences['USR-1001'].timezone='UTC';delete s.preferences['USR-1001'].preferredInput;delete s.preferences['USR-1001'].playbackRate;localStorage.setItem('stethofuse-demo-v1',JSON.stringify(s));});await go(a,'/app/settings?section=recording');assert.equal(await a.getByLabel('Preferred input').inputValue(),'Ask each time');assert.equal(await a.getByLabel('Playback speed').inputValue(),'1');assert.equal((await state(a)).preferences['USR-1001'].timezone,'UTC');
 });
 await check('Recording default options match the new-recording form',async()=>{
  await a.getByLabel('Default recording site').selectOption('Left lateral chest');await saved(a);await go(a,'/app/recordings/new');assert.equal(await a.getByLabel('Auscultation site').inputValue(),'Left lateral chest');
 });
 await check('Every modal title has a unique ID and correct accessible name',async()=>{
  await go(a,'/app/profile');await a.getByRole('button',{name:'About this demonstration identity'}).click();await a.getByRole('dialog',{name:'A clearly separated demo'}).waitFor();const ids=await a.locator('dialog').evaluateAll(elements=>elements.map(e=>e.getAttribute('aria-labelledby')));assert.equal(new Set(ids).size,ids.length);await a.screenshot({path:path.join(out,'unique-modal.png'),fullPage:true});await a.locator('dialog[open]').getByRole('button',{name:'Close dialog'}).click();
 });
 await check('Account menu supports arrow keys, Home/End and Escape focus restoration',async()=>{
  const trigger=a.locator('.account-button');await trigger.focus();await a.keyboard.press('ArrowDown');await a.getByRole('menu').waitFor();await a.waitForFunction(()=>document.activeElement?.textContent?.includes('Your profile'));await a.keyboard.press('ArrowDown');assert.match(await a.locator(':focus').innerText(),/Personal settings/);await a.keyboard.press('End');assert.match(await a.locator(':focus').innerText(),/Sign out/);await a.keyboard.press('Home');assert.match(await a.locator(':focus').innerText(),/Your profile/);await a.keyboard.press('Escape');assert.equal(await a.getByRole('menu').count(),0);assert.equal(await trigger.evaluate(e=>document.activeElement===e),true);
 });
 await check('Closed mobile navigation is inert; open drawer traps focus, locks scroll and restores focus',async()=>{
  await a.setViewportSize({width:390,height:844});await a.waitForFunction(()=>document.querySelector('.sidebar')?.inert===true);await a.locator('.skip-link').focus();await a.keyboard.press('Tab');assert.equal(await a.evaluate(()=>!!document.activeElement.closest('.sidebar')),false);const trigger=a.getByRole('button',{name:'Open navigation',exact:true});await trigger.click();await a.getByRole('dialog',{name:'Main navigation'}).waitFor();await a.waitForFunction(()=>!!document.activeElement.closest('.sidebar'));assert.equal(await a.evaluate(()=>document.body.style.overflow),'hidden');assert.equal(await a.locator('.app-main').evaluate(e=>e.inert),true);await a.keyboard.press('Shift+Tab');assert.match(await a.locator(':focus').innerText(),/Help & guidance/);await a.keyboard.press('Tab');assert.equal(await a.locator(':focus').getAttribute('class'),'sidebar-logo');await a.waitForFunction(()=>Math.abs(document.querySelector('.sidebar').getBoundingClientRect().x)<.1);const drawerBounds=await a.locator('.sidebar').boundingBox();assert.ok(Math.abs(drawerBounds.x)<.1);assert.equal(drawerBounds.width,250);await a.screenshot({path:path.join(out,'mobile-navigation.png'),fullPage:false});await a.keyboard.press('Escape');await a.waitForFunction(()=>document.querySelector('.sidebar')?.inert===true);assert.equal(await trigger.evaluate(e=>document.activeElement===e),true);assert.equal(await a.evaluate(()=>document.body.style.overflow),'');await a.setViewportSize({width:1440,height:1000});await a.waitForFunction(()=>!document.querySelector('.sidebar').inert);
 });
 await check('Scoped search excludes other owners and closes on same-route result',async()=>{
  await go(a,'/app/recordings/REC-1042');await a.getByRole('button',{name:'Search own recordings'}).click();await a.getByRole('dialog',{name:'Find a recording'}).waitFor();await a.getByLabel('Search your own recordings').fill('REC-1047');await a.getByText('No matching recordings in your account.',{exact:true}).waitFor();await a.getByLabel('Search your own recordings').fill('REC-1042');await a.locator('dialog[open]').getByRole('link',{name:/Morning chest recording/}).click();assert.equal(await a.locator('dialog[open]').count(),0);assert.match(a.url(),/REC-1042$/);
 });
 const b=await context.newPage();pages.push(b);watch(b);await login(b,'Sofia Chen');
 await check('Cross-tab revocation immediately denies the recipient and cannot be overwritten by a stale tab',async()=>{
  await go(b,'/app/recordings/REC-1042');await b.getByRole('button',{name:'Play original',exact:true}).waitFor();await go(a,'/app/shared');await a.locator('tbody tr').filter({hasText:'ASN-401'}).getByRole('button',{name:'Revoke',exact:true}).click();await a.locator('dialog[open]').getByRole('button',{name:'Revoke access',exact:true}).click();await b.getByRole('heading',{name:'This recording is private.'}).waitFor();assert.equal(await b.getByRole('button',{name:'Play original',exact:true}).count(),0);await go(b,'/app/notifications');await b.getByRole('button',{name:'Mark all as read'}).click();await b.waitForTimeout(150);assert.equal((await state(a)).assignments.find(x=>x.id==='ASN-401').status,'revoked');assert.equal(await a.evaluate(()=>sessionStorage.getItem('stethofuse-demo-persona')),'USR-1001');assert.equal(await b.evaluate(()=>sessionStorage.getItem('stethofuse-demo-persona')),'USR-2001');assert.ok(await a.evaluate(()=>window.__storageEvents)<8);assert.ok(await b.evaluate(()=>window.__storageEvents)<8);
 });
 await check('Review-notification preference controls future assignment notifications across tabs',async()=>{
  await go(b,'/app/settings?section=notifications');await b.getByLabel('Review and access updates').uncheck();await saved(b);await a.waitForFunction(()=>JSON.parse(localStorage.getItem('stethofuse-demo-v1')).preferences['USR-2001'].reviewNotifications===false);const count=(await state(a)).notifications.filter(n=>n.userId==='USR-2001').length;await go(a,'/app/recordings/REC-1043');await a.getByRole('button',{name:'Share or assign'}).click();await a.getByLabel('Recipient').selectOption('USR-2001');await a.getByRole('button',{name:'Grant demo access'}).click();await a.waitForTimeout(150);assert.equal((await state(a)).notifications.filter(n=>n.userId==='USR-2001').length,count);await b.getByLabel('Review and access updates').check();await saved(b);await go(a,'/app/recordings/REC-1045');await a.getByRole('button',{name:'Share or assign'}).click();await a.getByLabel('Recipient').selectOption('USR-2001');await a.getByRole('button',{name:'Grant demo access'}).click();await a.waitForTimeout(150);assert.equal((await state(a)).notifications.filter(n=>n.userId==='USR-2001').length,count+1);
 });
 await check('Review decisions honor the owner notification preference; drafts do not send notices',async()=>{
  await go(a,'/app/settings?section=notifications');await a.getByLabel('Review and access updates').uncheck();await saved(a);const count=(await state(a)).notifications.filter(n=>n.userId==='USR-1001').length;const assignment=(await state(a)).assignments.find(x=>x.recordingId==='REC-1045'&&x.analystId==='USR-2001');await go(b,`/app/reviews/${assignment.id}`);await b.getByLabel('Review summary').fill('Demonstration observation only. Brief contact noise.');await b.getByRole('button',{name:'Save draft',exact:true}).click();await b.waitForTimeout(100);assert.equal((await state(a)).notifications.filter(n=>n.userId==='USR-1001').length,count);await b.getByRole('button',{name:'Submit review',exact:true}).click();await b.locator('dialog[open]').getByRole('button',{name:'Submit decision'}).click();await b.waitForTimeout(100);assert.equal((await state(a)).notifications.filter(n=>n.userId==='USR-1001').length,count);await a.getByLabel('Review and access updates').check();await saved(a);await b.getByLabel('Review summary').fill('Demonstration review updated. No clinical conclusion.');await b.getByRole('button',{name:'Submit review',exact:true}).click();await b.locator('dialog[open]').getByRole('button',{name:'Submit decision'}).click();await b.waitForTimeout(100);assert.equal((await state(a)).notifications.filter(n=>n.userId==='USR-1001').length,count+1);
 });
 await b.close();
 await check('Disabled job notifications suppress future completion notices; repeat run becomes Latest result',async()=>{
  await go(a,'/app/settings?section=notifications');await a.getByLabel('Processing updates').uncheck();await saved(a);const count=(await state(a)).notifications.filter(n=>n.userId==='USR-1001'&&n.title==='Demo separation is ready').length;await go(a,'/app/recordings/REC-1042');await a.getByRole('button',{name:'Request ensemble run'}).click();await a.waitForURL(/\/app\/processing\/JOB/);const jobId=a.url().split('/').pop();await a.waitForFunction(id=>JSON.parse(localStorage.getItem('stethofuse-demo-v1')).jobs.find(j=>j.id===id)?.status==='completed',jobId,{timeout:35000});const s=await state(a);assert.equal(s.notifications.filter(n=>n.userId==='USR-1001'&&n.title==='Demo separation is ready').length,count);const resultId=s.jobs.find(j=>j.id===jobId).resultId;await go(a,'/app/recordings/REC-1042');assert.equal(await a.getByRole('link',{name:'Latest result'}).getAttribute('href'),`/app/results/${resultId}`);assert.ok(s.results.some(r=>r.id==='RES-3100'));
 });
 await check('Enabled job notifications create a completion notice for the owner',async()=>{
  await go(a,'/app/settings?section=notifications');await a.getByLabel('Processing updates').check();await saved(a);await go(a,'/app/recordings/REC-1045');await a.getByRole('button',{name:'Request ensemble run'}).click();await a.waitForURL(/\/app\/processing\/JOB/);const jobId=a.url().split('/').pop();await a.waitForFunction(id=>JSON.parse(localStorage.getItem('stethofuse-demo-v1')).jobs.find(j=>j.id===id)?.status==='completed',jobId,{timeout:35000});const s=await state(a);const resultId=s.jobs.find(j=>j.id===jobId).resultId;assert.ok(s.notifications.some(n=>n.userId==='USR-1001'&&n.href===`/app/results/${resultId}`));
 });
 await check('Session expiry preserves the intended route and saved non-sensitive draft',async()=>{
  await go(a,'/app/recordings/new/upload');await a.getByLabel('Recording title',{exact:true}).fill('Recovery continuity example');await a.getByRole('button',{name:'Save draft',exact:true}).click();await a.getByRole('button',{name:'Switch demo account'}).click();await a.getByRole('button',{name:'Simulate session expiry'}).click();await a.getByRole('dialog',{name:'Your session has expired'}).getByRole('button',{name:'Sign in again'}).click();await a.waitForURL(/\/session-expired\?returnTo=/);assert.equal(new URL(a.url()).searchParams.get('returnTo'),'/app/recordings/new/upload');await a.getByRole('button',{name:'Sign in again'}).click();await a.waitForURL(/\/login\?returnTo=/);await a.locator('.demo-entry summary').click();await a.getByRole('button',{name:/Amina Rahman/}).click();await a.waitForURL(/\/app\/recordings\/new\/upload/);assert.equal(await a.getByLabel('Recording title',{exact:true}).inputValue(),'Recovery continuity example');
 });
 await check('No runtime errors during shared-state and keyboard checks',async()=>assert.deepEqual(failures,[]));
}catch(error){console.error(error);process.exitCode=1;}finally{await fs.writeFile(path.join(out,'results.json'),JSON.stringify({date:new Date().toISOString(),browser:await browser.version(),mode:'Real headless Chrome, desktop and 390px viewport emulation; isolated fictional fixtures',results,errors:failures},null,2));await browser.close();}
