import {useEffect,useMemo,useState,type ReactNode} from 'react';
import {Link,Navigate,useLocation,useNavigate,useSearchParams} from 'react-router-dom';
import {ArrowLeft,ArrowRight,ArrowSquareOut,Bell,CheckCircle,CaretRight,Code,Database,Download,FileText,GearSix,Globe,IdentificationCard,Info,LinkSimple,LockKey,MagnifyingGlass,Palette,ShareNetwork,ShieldCheck,SlidersHorizontal,Stack,UserCircle,Users,Waveform} from '@phosphor-icons/react';
import {Badge,Button,CopyId,Empty,Field,Modal,Notice,PageHeading,Pagination,Panel,SaveBar,StatStrip,Status,Table,Tabs,UnsavedGuard,useError} from '../components/ui';
import {WinterArt,WinterNote} from '../components/WinterArt';
import {canAccess,formatDate,roleLabel,useApp} from '../data/store';
import type {Assignment,AuditEvent,Role,UserPreferences,UserStatus} from '../data/types';
import {brand} from '../brand';
import './account-pages.css';

const bytes=(n:number)=>`${(n/1048576).toFixed(1)} MB`;
const initials=(name:string)=>name.split(' ').map(n=>n[0]).slice(0,2).join('');
const dateIn=(date:string,from:string,to:string)=>!((from&&date.slice(0,10)<from)||(to&&date.slice(0,10)>to));
const roles:Role[]=['staff','analyst','admin'];
const statuses:UserStatus[]=['active','pending','disabled'];
function AccountError({message}:{message:string}){return message?<Notice tone="danger">{message}</Notice>:null;}
function AccountMedallion({children}:{children:ReactNode}){return <span className="account-medallion" aria-hidden="true">{children}</span>;}

export default function AccountPages(){
 const {pathname}=useLocation();const {user}=useApp();
 if(pathname.startsWith('/app/admin')&&user?.role!=='admin')return <Navigate to="/403" replace/>;
 if(pathname==='/app/admin')return <AdminOverview/>;
 if(pathname==='/app/admin/users')return <AdminUsers/>;
 if(pathname.startsWith('/app/admin/users/'))return <UserDetail key={pathname} id={decodeURIComponent(pathname.split('/').pop()||'')}/>;
 if(pathname==='/app/admin/records')return <AdminRecords/>;
 if(pathname==='/app/admin/assignments')return <AdminAssignments/>;
 if(pathname==='/app/admin/ensemble')return <EnsembleConfiguration/>;
 if(pathname==='/app/admin/audit')return <AuditLog/>;
 if(pathname==='/app/admin/settings')return <SystemSettings/>;
 if(pathname==='/app/profile')return <Profile key={user?.id}/>;
 if(pathname==='/app/settings')return <PersonalSettings key={user?.id}/>;
 if(pathname==='/app/notifications')return <Notifications/>;
 if(pathname==='/app/help')return <Help/>;
 return <Navigate to="/404" replace/>;
}

function AdminOverview(){
 const {state}=useApp();const active=state.users.filter(u=>u.status==='active').length;
 const running=state.jobs.filter(j=>['processing','queued'].includes(j.status)).length;
 const failed=state.jobs.filter(j=>j.status==='failed');
 return <>
  <PageHeading eyebrow="Administration" title="A clear view of the workspace." description="Account health and operational metadata, without opening anyone’s private recordings." actions={<Button to="/app/admin/users" variant="secondary"><Users size={17}/>Manage users</Button>}/>
  <Notice title="Fictional demonstration">All figures below come from local fixtures. No live service, storage system or processing worker is connected.</Notice>
  <StatStrip items={[{label:'Active accounts',value:active,detail:`${state.users.length} accounts in total`},{label:'Active jobs',value:running,detail:'Simulated stages only'},{label:'Recording metadata',value:state.recordings.length,detail:`${bytes(state.recordings.reduce((n,r)=>n+r.size,0))} declared size`}]}/>
  <div className="two-column section-gap account-overview-grid">
   <Panel title="Accounts at a glance" description="Access is deliberately scoped by ownership and assignment." className="account-summary-panel">
    {roles.map(role=><div className="list-row account-role-row" key={role}><AccountMedallion>{role==='admin'?<ShieldCheck size={22}/>:role==='analyst'?<Waveform size={22}/>:<UserCircle size={22}/>}</AccountMedallion><div><strong>{roleLabel(role)}</strong><p>{role==='admin'?'Manage accounts and operational metadata':role==='analyst'?'Review explicitly assigned recordings':'Manage personal recordings and ensemble runs'}</p></div><Badge>{state.users.filter(u=>u.role===role).length}</Badge></div>)}
    <div className="account-panel-foot"><Link className="inline-link" to="/app/admin/users?status=pending">Review pending accounts <ArrowRight size={16}/></Link></div>
   </Panel>
   <Panel title="Needs attention" description="Operational events, not assessments of recording quality." className="account-summary-panel">
    {failed.length?failed.map(job=><div className="list-row" key={job.id}><Info size={20}/><div><strong>Processing interrupted</strong><p><code>{job.id}</code> · Owner <code>{job.ownerId}</code></p><small className="muted">{job.error}</small></div><Status value="failed"/></div>):<Empty title="No failed jobs" description="Any simulated processing failures will appear here."/>}
    <div className="account-panel-foot"><Link className="inline-link" to="/app/admin/records?status=failed">Inspect job metadata <ArrowRight size={16}/></Link></div>
   </Panel>
  </div>
  <Panel className="section-gap account-table-panel" title="Recent administrative activity" actions={<Link className="inline-link" to="/app/admin/audit">All audit events <ArrowRight size={16}/></Link>}>
   <Table headers={['Event','Actor','Target','Date','Outcome']} caption="Recent administrative activity">{state.audit.slice(0,5).map(event=><tr key={event.id}><td><strong>{event.action}</strong><small>{event.id}</small></td><td><code>{event.actorId}</code></td><td><code>{event.targetId}</code></td><td>{formatDate(event.time)}</td><td><Status value={event.outcome}/></td></tr>)}</Table>
  </Panel>
  <Notice title="Administrative access is not audio access">Playback, waveforms, spectrograms and downloads require ownership or an explicit share. There is no impersonation feature or password/reset-link viewer.</Notice>
 </>;
}

function AdminUsers(){
 const {state}=useApp();const [params,setParams]=useSearchParams();
 const [search,setSearch]=useState(params.get('q')||'');const [role,setRole]=useState(params.get('role')||'all');const [status,setStatus]=useState(params.get('status')||'all');const [provider,setProvider]=useState('all');const [from,setFrom]=useState('');const [to,setTo]=useState('');const [sort,setSort]=useState('name');const [page,setPage]=useState(1);
 const filtered=useMemo(()=>state.users.filter(u=>[u.id,u.name,u.email].join(' ').toLowerCase().includes(search.toLowerCase())&&(role==='all'||u.role===role)&&(status==='all'||u.status===status)&&(provider==='all'||u.identities.some(p=>p.provider===provider))&&dateIn(u.createdAt,from,to)).sort((a,b)=>sort==='created'?b.createdAt.localeCompare(a.createdAt):sort==='id'?a.id.localeCompare(b.id):sort==='recent'?b.lastActive.localeCompare(a.lastActive):a.name.localeCompare(b.name)),[state.users,search,role,status,provider,from,to,sort]);
 useEffect(()=>{setPage(1);},[search,role,status,provider,from,to,sort]);
 function clear(){setSearch('');setRole('all');setStatus('all');setProvider('all');setFrom('');setTo('');setSort('name');setParams({});}
 return <><PageHeading eyebrow="Administration" title="People & permissions" description="Find a fictional account, inspect its metadata and manage appropriate access. Public signup never grants privileged roles."/>
  <div className="filter-bar account-primary-filters"><Field label="Name, email or User ID" className="search-field"><input type="search" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search USR-1001, name or email…"/></Field><Field label="Role"><select value={role} onChange={e=>setRole(e.target.value)}><option value="all">All roles</option>{roles.map(r=><option key={r} value={r}>{roleLabel(r)}</option>)}</select></Field><Field label="Status"><select value={status} onChange={e=>setStatus(e.target.value)}><option value="all">All statuses</option>{statuses.map(s=><option key={s}>{s}</option>)}</select></Field><Field label="Provider"><select value={provider} onChange={e=>setProvider(e.target.value)}><option value="all">All providers</option><option value="password">Email / password</option><option value="google">Google</option></select></Field></div>
  <div className="filter-bar account-secondary-filters"><Field label="Joined from"><input type="date" value={from} onChange={e=>setFrom(e.target.value)}/></Field><Field label="Joined through"><input type="date" min={from} value={to} onChange={e=>setTo(e.target.value)}/></Field><Field label="Sort"><select value={sort} onChange={e=>setSort(e.target.value)}><option value="name">Name A–Z</option><option value="id">User ID</option><option value="created">Newest account</option><option value="recent">Recently active</option></select></Field><Button variant="ghost" onClick={clear}>Clear filters</Button></div>
  <Panel className="account-table-panel account-directory" title="Account directory" actions={<Badge>{filtered.length} {filtered.length===1?'account':'accounts'}</Badge>}>{filtered.length?<><p className="account-table-hint">Scroll the table horizontally for status, provider and actions.</p><Table headers={['Account','User ID','Role','Status','Provider','Joined','']} caption="User management search results">{filtered.slice((page-1)*5,page*5).map(u=><tr key={u.id}><td><Link className="account-person" to={`/app/admin/users/${u.id}`}><span className="avatar" aria-hidden="true">{initials(u.name)}</span><span><strong>{u.name}</strong><small>{u.email}</small></span></Link></td><td><CopyId value={u.id}/></td><td>{roleLabel(u.role)}</td><td><Status value={u.status}/></td><td>{u.identities.map(i=>i.provider==='password'?'Password':'Google').join(' + ')}</td><td>{formatDate(u.createdAt)}</td><td><Button variant="ghost" to={`/app/admin/users/${u.id}`}>View details <ArrowRight size={14}/></Button></td></tr>)}</Table><Pagination page={page} total={filtered.length} pageSize={5} onChange={setPage}/></>:<Empty title="No accounts match" description="Try a complete User ID, a shorter name or fewer filters." action={<Button variant="secondary" onClick={clear}>Clear filters</Button>}/>}</Panel>
  <Notice title="Protecting account boundaries">This directory contains fictional identity and usage metadata only. Role changes do not grant administrators permission to listen to private files.</Notice>
 </>;
}

function UserDetail({id}:{id:string}){
 const {state,user,updateUser}=useApp();const account=state.users.find(u=>u.id===id);const [role,setRole]=useState<Role>(account?.role||'staff');const [status,setStatus]=useState<UserStatus>(account?.status||'active');const [confirm,setConfirm]=useState(false);const {error,run}=useError();
 if(!account)return <Empty title="Account not found" description="This User ID is not available in the fictional directory." action={<Button to="/app/admin/users" variant="secondary">Back to users</Button>}/>;
 const records=state.recordings.filter(r=>r.ownerId===id);const jobs=state.jobs.filter(j=>j.ownerId===id);const lastAdmin=account.role==='admin'&&account.status==='active'&&state.users.filter(u=>u.role==='admin'&&u.status==='active').length===1;const dirty=role!==account.role||status!==account.status;
 return <><UnsavedGuard when={dirty}/><Link className="inline-link" to="/app/admin/users"><ArrowLeft size={16}/>All users</Link><PageHeading eyebrow="Account metadata" title={account.name} description={<><CopyId value={account.id}/> <span className="account-inline-note">{account.id===user?.id?'Your administrator account':'Fictional demonstration account'}</span></>}/>
  <StatStrip items={[{label:'Own recordings',value:records.length},{label:'Declared storage',value:bytes(records.reduce((n,r)=>n+r.size,0))},{label:'Processing runs',value:jobs.length}]}/>
  <div className="two-column section-gap"><Panel title="Identity & activity"><dl className="metadata"><div><dt>Name</dt><dd>{account.name}</dd></div><div><dt>Email</dt><dd className="account-wrap">{account.email}</dd></div><div><dt>Verification</dt><dd><Status value={account.verified?'verified':'pending'}/></dd></div><div><dt>Account status</dt><dd><Status value={account.status}/></dd></div><div><dt>Created</dt><dd>{formatDate(account.createdAt)}</dd></div><div><dt>Last active</dt><dd>{formatDate(account.lastActive)}</dd></div></dl><hr/><h3 className="account-subheading">Linked identity providers</h3>{account.identities.map(i=><div className="list-row" key={i.provider}><ShieldCheck size={20}/><div><strong>{i.provider==='password'?'Email / password':'Google'}</strong><p>Linked {formatDate(i.linkedAt)}</p></div></div>)}<p className="note-text">Passwords, provider tokens, recovery URLs and private profile content are never shown.</p></Panel>
   <Panel title="Role & status" description="Changes apply only to this browser’s fictional account data."><Field label="Application role"><select value={role} onChange={e=>setRole(e.target.value as Role)}>{roles.map(r=><option key={r} value={r}>{roleLabel(r)}</option>)}</select></Field><Field label="Account status"><select value={status} onChange={e=>setStatus(e.target.value as UserStatus)}>{statuses.map(s=><option key={s}>{s}</option>)}</select></Field>{lastAdmin&&<Notice title="Last active administrator">Disabling or demoting this account is blocked. Another trusted administrator must be active first; there is no arbitrary two-admin limit.</Notice>}<AccountError message={error}/><SaveBar dirty={dirty} onSave={()=>setConfirm(true)} onCancel={()=>{setRole(account.role);setStatus(account.status);}} label="Review changes"/></Panel></div>
  <Panel className="section-gap" title="Account audit timeline" description="Safe operational metadata related to this account.">{state.audit.filter(e=>e.targetId===id||e.actorId===id).length?state.audit.filter(e=>e.targetId===id||e.actorId===id).slice(0,12).map(e=><div className="list-row" key={e.id}><div><strong>{e.action}</strong><p>{e.detail}</p><time>{formatDate(e.time)} · {e.actorId}</time></div><Status value={e.outcome}/></div>):<Empty title="No account changes yet" description="Role and status changes will create an audit event here."/>}</Panel>
  <Notice>Recording counts are metadata. To access audio, use your own workspace or an explicit content share; this page does not provide private playback.</Notice>
  <Modal open={confirm} onClose={()=>setConfirm(false)} title="Confirm account changes" footer={<><Button variant="secondary" onClick={()=>setConfirm(false)}>Cancel</Button><Button onClick={()=>run(()=>{updateUser(id,{role,status});setConfirm(false);})}>Confirm changes</Button></>}><p>You are changing <strong>{account.name}</strong> (<code>{id}</code>).</p><dl className="metadata"><div><dt>Role</dt><dd>{roleLabel(account.role)} → {roleLabel(role)}</dd></div><div><dt>Status</dt><dd>{account.status} → {status}</dd></div></dl><Notice>New permissions take effect in the demo immediately. Real authorization must be enforced by the backend.</Notice><AccountError message={error}/></Modal>
 </>;
}

function AdminRecords(){
 const {state}=useApp();const [params]=useSearchParams();const [search,setSearch]=useState('');const [source,setSource]=useState('all');const [status,setStatus]=useState(params.get('status')||'all');const [from,setFrom]=useState('');const [sort,setSort]=useState('newest');const [page,setPage]=useState(1);const [selected,setSelected]=useState('');
 const statusOf=(rid:string)=>state.jobs.find(j=>j.recordingId===rid)?.status||'not processed';
 const records=state.recordings.filter(r=>[r.id,r.ownerId].join(' ').toLowerCase().includes(search.toLowerCase())&&(source==='all'||r.source===source)&&(status==='all'||statusOf(r.id)===status)&&dateIn(r.createdAt,from,'')).sort((a,b)=>sort==='owner'?a.ownerId.localeCompare(b.ownerId):sort==='size'?b.size-a.size:b.createdAt.localeCompare(a.createdAt));
 useEffect(()=>setPage(1),[search,source,status,from,sort]);const current=state.recordings.find(r=>r.id===selected);
 return <><PageHeading eyebrow="Administration" title="Recording operations" description="Global IDs, processing states and declared storage. Recording content and notes remain private."/>
  <div className="filter-bar"><Field label="Recording ID or owner ID" className="search-field"><input type="search" value={search} onChange={e=>setSearch(e.target.value)} placeholder="REC-1042 or USR-1001"/></Field><Field label="Source"><select value={source} onChange={e=>setSource(e.target.value)}><option value="all">All sources</option><option value="upload">Upload</option><option value="device">Device</option><option value="sample">Demo sample</option></select></Field><Field label="Processing status"><select value={status} onChange={e=>setStatus(e.target.value)}>{['all','not processed','queued','processing','completed','partial','failed','cancelled'].map(s=><option key={s} value={s}>{s==='all'?'All statuses':s}</option>)}</select></Field><Field label="Created from"><input type="date" value={from} onChange={e=>setFrom(e.target.value)}/></Field><Field label="Sort"><select value={sort} onChange={e=>setSort(e.target.value)}><option value="newest">Newest first</option><option value="owner">Owner ID</option><option value="size">Declared size</option></select></Field></div>
  {records.length?<><Table headers={['Recording ID','Owner','Source','Created','Declared size','Latest job','']} caption="Operational recording metadata">{records.slice((page-1)*6,page*6).map(r=><tr key={r.id}><td><CopyId value={r.id}/>{r.archived&&<small>Archived by owner</small>}</td><td><Link to={`/app/admin/users/${r.ownerId}`}><code>{r.ownerId}</code></Link></td><td>{r.source}</td><td>{formatDate(r.createdAt)}</td><td>{bytes(r.size)}</td><td><Status value={statusOf(r.id)}/></td><td><Button variant="ghost" onClick={()=>setSelected(r.id)}>Job metadata</Button></td></tr>)}</Table><Pagination page={page} total={records.length} onChange={setPage}/></>:<Empty title="No matching metadata" description="Try a different recording/owner ID, date or processing status." action={<Button variant="secondary" onClick={()=>{setSearch('');setSource('all');setStatus('all');setFrom('');}}>Clear filters</Button>}/>}
  <Notice title="Audio access is not implied"><p>Titles, recording notes, playback and downloads are intentionally excluded here. A real backend must authorize every content endpoint independently.</p></Notice>
  <Modal open={!!current} onClose={()=>setSelected('')} title="Processing metadata">{current&&<><CopyId value={current.id}/><p>Owner: <code>{current.ownerId}</code></p><dl className="metadata"><div><dt>Sample rate</dt><dd>{current.sampleRate.toLocaleString()} Hz</dd></div><div><dt>Channels</dt><dd>{current.channels}</dd></div></dl><hr/>{state.jobs.filter(j=>j.recordingId===current.id).length?state.jobs.filter(j=>j.recordingId===current.id).map(j=><div className="account-job" key={j.id}><div className="toolbar"><CopyId value={j.id}/><Status value={j.status}/></div><p>Ensemble {j.ensembleVersion} · Stage {j.stage} / 5</p><small>{formatDate(j.startedAt)}</small>{j.error&&<Notice tone="warning">{j.error}</Notice>}</div>):<p>No ensemble run has been requested.</p>}<Notice>No original audio or separated outputs are exposed by this metadata view.</Notice></>}</Modal>
 </>;
}

function AdminAssignments(){
 const {state,reassign,revoke}=useApp();const [search,setSearch]=useState('');const [analyst,setAnalyst]=useState('all');const [status,setStatus]=useState('all');const [from,setFrom]=useState('');const [page,setPage]=useState(1);const [sort,setSort]=useState('newest');const [selection,setSelection]=useState<Assignment|null>(null);const [action,setAction]=useState<'reassign'|'revoke'>('reassign');const [recipient,setRecipient]=useState('');const {error,setError,run}=useError();
 const analysts=state.users.filter(u=>u.role==='analyst'&&u.status==='active');
 const rows=state.assignments.filter(a=>[a.id,a.recordingId,a.ownerId,a.analystId].join(' ').toLowerCase().includes(search.toLowerCase())&&(analyst==='all'||a.analystId===analyst)&&(status==='all'||a.status===status)&&dateIn(a.createdAt,from,'')).sort((a,b)=>sort==='owner'?a.ownerId.localeCompare(b.ownerId):sort==='status'?a.status.localeCompare(b.status):b.createdAt.localeCompare(a.createdAt));
 useEffect(()=>setPage(1),[search,analyst,status,from,sort]);
 function open(a:Assignment,type:'reassign'|'revoke'){setSelection(a);setAction(type);setRecipient('');setError('');}
 return <><PageHeading eyebrow="Administration" title="Assignments & access" description="Manage explicit access metadata. Reassigning does not transfer ownership, and revocation removes content access immediately in this demo."/>
  <div className="filter-bar"><Field label="Assignment, recording or owner ID" className="search-field"><input type="search" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search assignment metadata…"/></Field><Field label="Assigned account"><select value={analyst} onChange={e=>setAnalyst(e.target.value)}><option value="all">All assigned accounts</option>{state.users.map(u=><option key={u.id} value={u.id}>{u.name} · {u.id}</option>)}</select></Field><Field label="Status"><select value={status} onChange={e=>setStatus(e.target.value)}>{['all','pending','in-review','reviewed','re-record','revoked'].map(s=><option key={s} value={s}>{s==='all'?'All statuses':s.replaceAll('-',' ')}</option>)}</select></Field><Field label="Assigned from"><input type="date" value={from} onChange={e=>setFrom(e.target.value)}/></Field><Field label="Sort"><select value={sort} onChange={e=>setSort(e.target.value)}><option value="newest">Newest first</option><option value="owner">Owner ID</option><option value="status">Status</option></select></Field></div>
  {rows.length?<><Table headers={['Assignment','Recording / owner','Assigned account','Access','Status','Date','Actions']} caption="Explicit assignment metadata">{rows.slice((page-1)*6,page*6).map(a=><tr key={a.id}><td><CopyId value={a.id}/></td><td><strong><code>{a.recordingId}</code></strong><small>{a.ownerId}</small></td><td><strong>{state.users.find(u=>u.id===a.analystId)?.name||a.analystId}</strong><small>{a.analystId}</small></td><td>{a.permission}</td><td><Status value={a.status}/></td><td>{formatDate(a.createdAt)}</td><td><div className="row-actions"><Button variant="ghost" onClick={()=>open(a,'reassign')}>{a.status==='revoked'?'Create new assignment':'Reassign'}</Button>{a.status!=='revoked'&&<Button variant="ghost" onClick={()=>open(a,'revoke')}>Revoke</Button>}</div></td></tr>)}</Table><Pagination page={page} total={rows.length} onChange={setPage}/></>:<Empty title="No matching assignments" description="Try fewer filters. Owners create new shares in their personal recording workspace." action={<Button variant="secondary" onClick={()=>{setSearch('');setAnalyst('all');setStatus('all');setFrom('');}}>Clear filters</Button>}/>}
  <Link className="inline-link" to="/app/admin/audit?query=Access">Inspect the access audit trail <ArrowRight size={16}/></Link>
  <Modal open={!!selection} onClose={()=>setSelection(null)} title={action==='revoke'?'Revoke content access':'Confirm new assignment'} footer={<><Button variant="secondary" onClick={()=>setSelection(null)}>Cancel</Button><Button variant={action==='revoke'?'danger':'primary'} disabled={action==='reassign'&&!recipient} onClick={()=>run(()=>{if(!selection)return;if(action==='revoke')revoke(selection.id);else {if(!recipient)throw new Error('Choose an active analyst.');reassign(selection.id,recipient);}setSelection(null);})}>{action==='revoke'?'Revoke access':'Confirm assignment'}</Button></>}>{selection&&<><p>Assignment <strong>{selection.id}</strong> for <code>{selection.recordingId}</code>.</p>{action==='revoke'?<Notice tone="warning">The assigned account will lose access, including through a previously opened direct link. Existing audit metadata is retained.</Notice>:<><Field label="Active analyst"><select value={recipient} onChange={e=>setRecipient(e.target.value)}><option value="">Choose analyst</option>{analysts.filter(a=>a.id!==selection.analystId).map(a=><option value={a.id} key={a.id}>{a.name} · {a.id}</option>)}</select></Field><p className="note-text">The current assignment is revoked and preserved in history. A new assignment ID begins pending for the selected analyst. Ownership and permission type remain unchanged; existing review notes are not transferred. An audit event records this action. To grant access again to the same recipient, the recording owner can use its sharing controls.</p>{!analysts.some(a=>a.id!==selection.analystId)&&<Notice>No different active analyst is available. A different existing account can be granted the analyst role through Users before creating a new assignment.</Notice>}</>}<AccountError message={error}/></>}</Modal>
 </>;
}

function EnsembleConfiguration(){
 const {state,saveSystem}=useApp();const [fusion,setFusion]=useState(state.system.fusion);const [confirm,setConfirm]=useState(false);const [candidate,setCandidate]=useState<number|null>(null);const {error,run}=useError();const dirty=fusion!==state.system.fusion;
 const candidates=[{name:'NeoSSNet',kind:'Neural separation candidate',version:'Research candidate',attribution:'Upstream code: yangyipoh / Neonatal-Chest-Sound-Separation-using-Deep-Learning, also referenced by this project. Paper authors, exact revision and redistribution terms require verification before live use.',link:'https://github.com/yangyipoh/Neonatal-Chest-Sound-Separation-using-Deep-Learning',linkLabel:'Upstream source and README',status:'Not connected'},{name:'NMF / NMCF',kind:'Literature-faithful factorization candidate',version:'Verification pending',attribution:'Paper title, authors and method correspondence are not yet verified. A generic NMF baseline is not represented as the complete published method.',status:'Verification pending'},{name:'DAE-NMF-VMD',kind:'Hybrid denoising / decomposition candidate',version:'Verification pending',attribution:'Paper title, authors, architecture and implementation equivalence require verification. No completed expert is claimed.',status:'Verification pending'}];
 return <><UnsavedGuard when={dirty}/><PageHeading eyebrow="Administration" title="Ensemble configuration" description="A transparent view of research candidates and experiment intent. The personal workspace always requests one ensemble service."/>
  <div className="account-ensemble-disclosure"><Notice title="Frontend demonstration only">No training, inference, model weights or live pipeline configuration is changed here. Candidate availability is not a clinical or performance claim.</Notice></div>
  <Panel className="account-experts" title="Candidate experts" description="Provenance must be confirmed before activating a real expert." actions={<div className="account-expert-decoration" aria-hidden="true"><WinterArt kind="signalFine" className="account-heading-signal winter-signal"/><p>Complementary methods.<br/>Stronger insights.</p></div>}>{candidates.map((c,index)=><article className="expert-row" key={c.name}><div className="expert-identity"><AccountMedallion>{index===0?<Waveform size={42}/>:index===1?<Stack size={42}/>:<ShareNetwork size={42}/>}</AccountMedallion><div><h3>{c.name}</h3><p>{c.kind}</p><Badge tone="warning">{c.status}</Badge></div></div><div className="expert-provenance"><dl className="metadata"><div><dt>Version</dt><dd>{c.version}</dd></div><div><dt>Experiment state</dt><dd>Not evaluated in this frontend</dd></div></dl><p>{c.attribution}</p>{c.link&&<a className="inline-link" href={c.link} target="_blank" rel="noreferrer">{c.linkLabel}<ArrowRight size={15}/></a>}</div><div className="expert-inspect"><button type="button" aria-label={`View provenance for ${c.name}`} onClick={()=>setCandidate(index)}><CaretRight size={25}/></button></div></article>)}</Panel>
  <Panel className="section-gap account-fusion" title="Fusion experiment" description="This label is attached to newly simulated runs. Historical results retain their own provenance."><div className="account-fusion-body"><div className="account-fusion-controls"><Field label="Demonstration fusion configuration"><SlidersHorizontal size={21} aria-hidden="true"/><select value={fusion} onChange={e=>setFusion(e.target.value)}><option>Weighted consensus · demonstration</option><option>Fixed fusion · experiment planned</option><option>Adaptive fusion · experiment planned</option></select></Field><Notice>Fixed and adaptive fusion remain experiment stages. No superiority, separation-quality score or measured improvement is implied.</Notice></div><div className="account-fusion-scenery" aria-hidden="true"><WinterArt kind="fusionForest"/></div></div><AccountError message={error}/>{dirty&&<SaveBar dirty={dirty} onSave={()=>setConfirm(true)} onCancel={()=>setFusion(state.system.fusion)} label="Review configuration"/>}</Panel><Modal open={candidate!==null} onClose={()=>setCandidate(null)} title={candidate===null?'Candidate provenance':candidates[candidate].name}>{candidate!==null&&<><Badge tone="warning">{candidates[candidate].status}</Badge><p>{candidates[candidate].attribution}</p><Notice>No training, inference or evaluation is connected in this frontend.</Notice>{candidates[candidate].link&&<a className="inline-link" href={candidates[candidate].link} target="_blank" rel="noreferrer">{candidates[candidate].linkLabel}<ArrowRight size={15}/></a>}</>}</Modal>
  <Modal open={confirm} onClose={()=>setConfirm(false)} title="Save demonstration configuration" footer={<><Button variant="secondary" onClick={()=>setConfirm(false)}>Cancel</Button><Button onClick={()=>run(()=>{saveSystem({fusion});setConfirm(false);})}>Save demo configuration</Button></>}><p>New simulated ensemble runs will show <strong>{fusion}</strong>.</p><p>No Python, ML, training or deployed service setting will change.</p><AccountError message={error}/></Modal>
 </>;
}

function AuditLog(){
 const {state}=useApp();const [params]=useSearchParams();const [search,setSearch]=useState(params.get('query')||'');const [action,setAction]=useState('all');const [outcome,setOutcome]=useState('all');const [from,setFrom]=useState('');const [to,setTo]=useState('');const [sort,setSort]=useState('newest');const [page,setPage]=useState(1);const [selected,setSelected]=useState<AuditEvent|null>(null);
 const rows=state.audit.filter(e=>[e.id,e.actorId,e.targetId,e.action].join(' ').toLowerCase().includes(search.toLowerCase())&&(action==='all'||e.action===action)&&(outcome==='all'||e.outcome===outcome)&&dateIn(e.time,from,to)).sort((a,b)=>sort==='oldest'?a.time.localeCompare(b.time):b.time.localeCompare(a.time));
 useEffect(()=>setPage(1),[search,action,outcome,from,to,sort]);
 return <><PageHeading eyebrow="Administration" title="Audit trail" description="Who changed what, and when. Safe metadata only; credentials, reset URLs and private recording notes are excluded."/>
  <div className="filter-bar account-audit-filters"><Field label="Event, actor, target ID or action" className="search-field"><MagnifyingGlass size={20} aria-hidden="true"/><input type="search" placeholder="Search safe event metadata…" value={search} onChange={e=>setSearch(e.target.value)}/></Field><Field label="Action"><select value={action} onChange={e=>setAction(e.target.value)}><option value="all">All actions</option>{[...new Set(state.audit.map(e=>e.action))].map(a=><option key={a}>{a}</option>)}</select></Field><Field label="Outcome"><select value={outcome} onChange={e=>setOutcome(e.target.value)}><option value="all">All outcomes</option><option value="success">Success</option><option value="blocked">Blocked</option></select></Field><Field label="From"><input type="date" value={from} onChange={e=>setFrom(e.target.value)}/></Field><Field label="Through"><input type="date" min={from} value={to} onChange={e=>setTo(e.target.value)}/></Field><Field label="Sort"><select value={sort} onChange={e=>setSort(e.target.value)}><option value="newest">Newest first</option><option value="oldest">Oldest first</option></select></Field></div>
  <Panel className="account-table-panel account-audit"><div className="panel-heading"><div className="account-heading-with-icon"><AccountMedallion><Waveform size={25}/></AccountMedallion><h2>Audit events</h2></div><span className="account-result-count">{rows.length} {rows.length===1?'result':'results'}</span></div>{rows.length?<><Table headers={['Event','Actor ID','Target ID','Date / time','Outcome','Details']} caption="Administrative audit events">{rows.slice((page-1)*8,page*8).map(e=><tr key={e.id}><td><div className="account-audit-event"><span className="account-audit-timeline" aria-hidden="true"/><AccountMedallion><FileText size={26}/></AccountMedallion><div><strong>{e.action}</strong><small>{e.id}</small><small className="account-event-summary">{e.detail}</small></div></div></td><td><code>{e.actorId}</code></td><td><code>{e.targetId}</code></td><td>{formatDate(e.time)}<small>{new Date(e.time).toLocaleTimeString('en-GB',{hour:'2-digit',minute:'2-digit'})}</small></td><td><Status value={e.outcome}/></td><td><Button variant="ghost" onClick={()=>setSelected(e)}>Details<ArrowRight size={17}/></Button></td></tr>)}</Table><Pagination page={page} total={rows.length} pageSize={8} onChange={setPage}/></>:<Empty title="No matching events" description="Try a different ID, action, date or outcome." action={<Button variant="secondary" onClick={()=>{setSearch('');setAction('all');setOutcome('all');setFrom('');setTo('');}}>Clear filters</Button>}/>}</Panel><aside className="account-reference-note account-audit-note"><Notice title="Audit logs store safe operational metadata only.">Credentials, reset URLs and private recording notes are excluded. These local demonstration events are not immutable production audit records.</Notice><WinterArt kind="signalFine" className="winter-signal"/><p className="account-reference-quote" aria-hidden="true">Trusted tools for<br/>brighter tomorrows.</p></aside>
  <Modal open={!!selected} onClose={()=>setSelected(null)} title="Audit event details">{selected&&<><CopyId value={selected.id}/><h3 className="account-event-title">{selected.action}</h3><dl className="metadata"><div><dt>Actor</dt><dd><code>{selected.actorId}</code></dd></div><div><dt>Target</dt><dd><code>{selected.targetId}</code></dd></div><div><dt>Timestamp</dt><dd>{new Date(selected.time).toLocaleString('en-GB')}</dd></div><div><dt>Outcome</dt><dd><Status value={selected.outcome}/></dd></div></dl><hr/><p>{selected.detail}</p><Notice>This is a local demonstration event, not an immutable production audit record.</Notice></>}</Modal>
 </>;
}

function SystemSettings(){
 const {state,saveSystem}=useApp();const [max,setMax]=useState(String(state.system.maxUploadMB));const [retention,setRetention]=useState(String(state.system.retentionDays));const [maintenance,setMaintenance]=useState(state.system.maintenance);const [confirm,setConfirm]=useState(false);const {error,setError,run}=useError();const dirty=Number(max)!==state.system.maxUploadMB||Number(retention)!==state.system.retentionDays||maintenance!==state.system.maintenance;
 function review(){if(!Number.isInteger(Number(max))||Number(max)<1||Number(max)>250){setError('Enter an upload limit from 1 to 250 MB.');return;}if(!Number.isInteger(Number(retention))||Number(retention)<1||Number(retention)>365){setError('Enter a retention period from 1 to 365 days.');return;}setError('');setConfirm(true);}
 return <><UnsavedGuard when={dirty}/><PageHeading eyebrow="Administration" title="System preferences" description="Inspect configuration boundaries and save fictional operational preferences without changing deployment."/>
  <div className="two-column account-system-grid">
   <Panel className="account-system-limits"><div className="account-system-heading"><AccountMedallion><GearSix size={26}/></AccountMedallion><div><Badge>System configuration</Badge><h2>Demonstration limits</h2><p>Define safe limits for this demonstration environment.</p></div></div>
    <Field label="Maximum WAV upload size (MB)" hint="The frontend validates this limit. No server upload endpoint is configured."><input type="number" min="1" max="250" value={max} onChange={e=>setMax(e.target.value)}/></Field>
    <Field label="Presented retention period (days)" hint="Policy presentation only; no retention job or automatic deletion is running."><input type="number" min="1" max="365" value={retention} onChange={e=>setRetention(e.target.value)}/></Field>
    <label className="checkbox-row"><input type="checkbox" checked={maintenance} onChange={e=>setMaintenance(e.target.checked)}/><span>Remember maintenance-preview preference<p>This does not disable the live website. Open the recovery preview to inspect its presentation.</p></span></label>
    <div className="account-maintenance-link"><ArrowSquareOut size={23} aria-hidden="true"/><div><Link className="inline-link" to="/maintenance">Preview maintenance screen <ArrowRight size={17}/></Link><p>See how the maintenance mode looks to users.</p></div></div><AccountError message={error}/>
    <SaveBar dirty={dirty} onSave={review} onCancel={()=>{setMax(String(state.system.maxUploadMB));setRetention(String(state.system.retentionDays));setMaintenance(state.system.maintenance);setError('');}} label="Review settings"/>
   </Panel>
   <Panel className="account-system-integrations"><div className="account-system-heading"><AccountMedallion><LinkSimple size={27}/></AccountMedallion><div><Badge>External connections</Badge><h2>Integration status</h2><p>View how this workspace connects to external services.</p></div></div>
    <dl className="account-integration-list">
     <div><dt>Authentication</dt><dd><AccountMedallion><ShieldCheck size={23}/></AccountMedallion><div className="account-integration-value"><Badge tone="warning">Demo adapter</Badge><p>Firebase configuration and authorized provider flows are still required.</p></div></dd></div>
     <div><dt>Application API</dt><dd><AccountMedallion><Code size={23}/></AccountMedallion><div className="account-integration-value"><div className="account-config-value"><CopyId value={brand.apiBaseUrl}/></div><p>Configured boundary only. The mock adapter makes no request to private audio endpoints.</p></div></dd></div>
     <div><dt>Public origin</dt><dd className="account-wrap"><AccountMedallion><Globe size={23}/></AccountMedallion><div className="account-integration-value"><div className="account-config-value"><CopyId value={brand.publicOrigin}/></div><p>Read from brand configuration. DNS and callback settings are unchanged.</p></div></dd></div>
     <div><dt>Secrets</dt><dd><AccountMedallion><LockKey size={23}/></AccountMedallion><div className="account-integration-value"><Badge>Not available<span className="sr-only"> in this interface</span></Badge><p>No API-key, password, token or private-storage credential editor.</p></div></dd></div>
    </dl>
   </Panel>
  </div>
  <aside className="account-reference-note account-system-note"><Notice title="Demo workspace">These settings are fictional and local to this browser. They do not affect any real service or deployment.</Notice><WinterArt kind="signalFine" className="winter-signal"/><p className="account-reference-quote" aria-hidden="true">Small settings.<br/>Big possibilities.</p></aside>
  <Modal open={confirm} onClose={()=>setConfirm(false)} title="Confirm demo preferences" footer={<><Button variant="secondary" onClick={()=>setConfirm(false)}>Cancel</Button><Button onClick={()=>run(()=>{saveSystem({maxUploadMB:Number(max),retentionDays:Number(retention),maintenance});setConfirm(false);})}>Save demo preferences</Button></>}><p>Upload limit: <strong>{max} MB</strong>. Retention presentation: <strong>{retention} days</strong>.</p><Notice>No deployment, authentication, backend or actual retention policy will be changed.</Notice><AccountError message={error}/></Modal></>;
}

function Profile(){
 const {user,saveProfile}=useApp();const [name,setName]=useState(user?.name||'');const [confirm,setConfirm]=useState(false);const {error,setError,run}=useError();if(!user)return null;
 const dirty=name.trim()!==user.name;
 return <><UnsavedGuard when={dirty}/><PageHeading eyebrow="Your account" title="Profile" description="Your identity in the workspace. Application roles describe permissions, not verified professional credentials."/><div className="two-column account-profile-grid"><Panel title="Personal details" className="account-profile-details" actions={<AccountMedallion><UserCircle size={24}/></AccountMedallion>}><div className="profile-heading"><span className="avatar profile-avatar">{initials(name||user.name)}</span><div><strong>{user.name}</strong><p>Initials avatar · no external profile upload</p></div></div><Field label="Display name" error={error}><input value={name} maxLength={80} autoComplete="name" onChange={e=>setName(e.target.value)}/></Field><Field label="Email" hint="Email changes require provider reauthentication and verification."><input type="email" value={user.email} readOnly/></Field><Link className="inline-link" to="/app/settings?section=security">Manage account security <ArrowRight size={15}/></Link><SaveBar dirty={dirty} onSave={()=>{if(name.trim().length<2){setError('Enter a display name of at least two characters.');return;}run(()=>saveProfile({name}));}} onCancel={()=>{setName(user.name);setError('');}}/></Panel><Panel title="Account identity" className="account-profile-identity" actions={<AccountMedallion><IdentificationCard size={24}/></AccountMedallion>}><dl className="metadata"><div><dt>Application User ID</dt><dd><CopyId value={user.id}/></dd></div><div><dt>Role</dt><dd>{roleLabel(user.role)}</dd></div><div><dt>Email verification</dt><dd><Status value={user.verified?'verified':'pending'}/></dd></div><div><dt>Member since</dt><dd>{formatDate(user.createdAt)}</dd></div></dl><hr/>{user.identities.map(i=><div className="list-row" key={i.provider}><ShieldCheck size={20}/><div><strong>{i.provider==='password'?'Email / password':'Google'}</strong><p>Fictional linked identity · {formatDate(i.linkedAt)}</p></div></div>)}<Notice>Roles cannot be changed from Profile. Ask an authorized administrator if your application permissions need review.</Notice><Button variant="ghost" onClick={()=>setConfirm(true)}>About this demonstration identity</Button></Panel></div><Modal open={confirm} onClose={()=>setConfirm(false)} title="A clearly separated demo"><p>This is a fictional account. Its name and preferences are stored in this browser to demonstrate continuity.</p><p>No real password, session token or private recording is saved. Actual sign-in will use the configured authentication adapter and backend authorization.</p></Modal></>;
}

const settingsSections=[{id:'general',label:'General',icon:GearSix},{id:'appearance',label:'Appearance',icon:Palette},{id:'notifications',label:'Notifications',icon:Bell},{id:'security',label:'Security',icon:ShieldCheck},{id:'recording',label:'Recording defaults',icon:Waveform},{id:'data',label:'Data & storage',icon:Database}];
function PersonalSettings(){
 const {user,preferences,savePreferences,state,recordEvent,logout,notify}=useApp();const navigate=useNavigate();const [params,setParams]=useSearchParams();const requested=params.get('section')||'general';const section=settingsSections.some(s=>s.id===requested)?requested:'general';const [values,setValues]=useState<UserPreferences>(preferences);const [pendingSection,setPendingSection]=useState('');const [dialog,setDialog]=useState<'link'|'reauth'|'sessions'|'export'|'delete'|null>(null);const [deleteText,setDeleteText]=useState('');const {error,run}=useError();const dirty=JSON.stringify(values)!==JSON.stringify(preferences);
 if(!user)return null;const records=state.recordings.filter(r=>r.ownerId===user.id);const password=user.identities.some(i=>i.provider==='password');const hasGoogle=user.identities.some(i=>i.provider==='google');
 function change<K extends keyof UserPreferences>(key:K,value:UserPreferences[K]){setValues(v=>({...v,[key]:value}));}
 function go(id:string){if(dirty){setPendingSection(id);return;}setParams({section:id});}
 function save(){run(()=>{savePreferences(values);});}
 function exportMetadata(){const payload={demo:true,notice:'Fictional metadata only. No audio, passwords, tokens or provider secrets.',exportedAt:new Date().toISOString(),profile:{id:user!.id,name:user!.name,role:user!.role},preferences,recordings:records,jobs:state.jobs.filter(j=>j.ownerId===user!.id),results:state.results.filter(r=>r.ownerId===user!.id)};const url=URL.createObjectURL(new Blob([JSON.stringify(payload,null,2)],{type:'application/json'}));const anchor=document.createElement('a');anchor.href=url;anchor.download=`stethofuse-demo-${user!.id}.json`;anchor.click();setTimeout(()=>URL.revokeObjectURL(url),500);recordEvent('Demo metadata exported',user!.id,'Only the current fictional account’s metadata was downloaded. No audio or secrets.');setDialog(null);}
 const toggle=(key:'reducedMotion'|'snow'|'highContrast'|'emailNotifications'|'jobNotifications'|'reviewNotifications',title:string,description:string)=><label className="setting-row" key={key}><span><strong>{title}</strong><p>{description}</p></span><input type="checkbox" checked={values[key]} onChange={e=>change(key,e.target.checked)}/></label>;
 return <><UnsavedGuard when={dirty}/><PageHeading eyebrow="Your preferences" title="Make room for your way of working." description="Preferences belong to your account and remain available when you return to this browser."/><div className={`settings-layout account-settings account-settings-${section}`}><nav className="settings-nav" aria-label="Personal settings sections">{settingsSections.map(s=><button key={s.id} className={s.id===section?'active':''} aria-current={s.id===section?'page':undefined} onClick={()=>go(s.id)}><s.icon size={21} aria-hidden="true"/><span>{s.label}</span></button>)}</nav><section className="settings-content" aria-label={settingsSections.find(s=>s.id===section)?.label}>
  {section==='general'&&<><h2>General</h2><p className="account-section-description">A few useful defaults for dates and your working location.</p><Field label="Language" hint="English is the only implemented interface language."><select value="en" onChange={()=>{}}><option value="en">English</option></select></Field><Field label="Timezone"><select value={values.timezone} onChange={e=>change('timezone',e.target.value)}>{['Asia/Kuala_Lumpur','Asia/Singapore','Asia/Dubai','Europe/London','America/New_York','UTC'].map(z=><option key={z}>{z}</option>)}</select></Field><Field label="Date format"><select value={values.dateFormat} onChange={e=>change('dateFormat',e.target.value)}><option value="day-first">Day first · 24 Sep 2026</option><option value="month-first">Month first · Sep 24, 2026</option><option value="iso">ISO · 2026-09-24</option></select></Field><p className="note-text">Preview: {new Intl.DateTimeFormat('en-GB',{dateStyle:'long',timeStyle:'short',timeZone:values.timezone}).format(new Date('2026-09-24T08:30:00Z'))}</p></>}
  {section==='appearance'&&<><h2>Appearance & accessibility</h2><p className="account-section-description">The same calm winter palette, with motion and contrast adjusted to your needs.</p><div className="theme-swatch" aria-label="Approved winter palette"><span/><span/><span/><div><strong>StethoFuse winter</strong><small>Approved light theme · no alternate theme</small></div></div>{toggle('reducedMotion','Reduce nonessential motion','Use the static owl and remove decorative animation. System reduced-motion preferences also take precedence.')}{toggle('snow','Show delicate snow','Decorative snow appears only on public artwork, never over working controls. Reduced motion overrides this preference.')}{toggle('highContrast','Increase interface contrast','Strengthen text and borders while preserving the approved palette.')}<Notice>Animation is an enhancement. Every task remains available with a static owl and no snow.</Notice></>}
  {section==='notifications'&&<><h2>Notifications</h2><p className="account-section-description">Choose which local workflow updates appear. Nothing is sent outside this demonstration.</p>{toggle('jobNotifications','Processing updates','Show in-app updates when a simulated ensemble job finishes.')}{toggle('reviewNotifications','Review and access updates','Show assignment and review notifications for content you are authorized to access.')}{toggle('emailNotifications','Email preference','Remember your preference only. Email delivery is not configured and no email will be sent.')}<Notice title="Provider not configured">These are demo preferences. No transactional email provider or push-notification service is connected.</Notice><Link className="inline-link" to="/app/notifications">Open notification inbox <ArrowRight size={15}/></Link></>}
  {section==='security'&&<><h2>Security</h2><p className="account-section-description">Identity providers, reauthentication and session controls. No credentials are visible here.</p>{user.identities.map(i=><div className="list-row" key={i.provider}><ShieldCheck size={22}/><div><strong>{i.provider==='password'?'Email / password':'Google'}</strong><p>Linked {formatDate(i.linkedAt)} · demo identity</p></div><Badge>Linked</Badge></div>)}{password?<div className="setting-row"><div><strong>Password recovery</strong><p>Use the recovery flow. Existing passwords cannot be viewed or retrieved.</p></div><Button variant="secondary" to="/forgot-password">Reset password</Button></div>:<Notice>Google-only account: manage your password with Google. A local password must be added through an authorized provider-linking flow, not by matching email strings.</Notice>}<div className="setting-row"><div><strong>Identity linking</strong><p>{hasGoogle?'Google is already listed on this fictional account. Linking conflicts require provider verification.':'Connect Google only through provider reauthentication. Demo linking does not modify your identity.'}</p></div><Button variant="secondary" onClick={()=>setDialog('link')}>{hasGoogle?'Review linking':'Link Google'}</Button></div><div className="setting-row"><div><strong>Reauthentication</strong><p>Sensitive account changes require a fresh provider check in the real integration.</p></div><Button variant="secondary" onClick={()=>setDialog('reauth')}>Review status</Button></div><h3 className="account-subheading section-gap">Sessions</h3><div className="list-row"><LockKey size={20}/><div><strong>This browser</strong><p>Current fictional persona session. No device inventory or real provider token is stored.</p></div><Badge>Current</Badge></div><div className="toolbar section-gap"><Button variant="secondary" onClick={()=>setDialog('sessions')}>Sign out this browser</Button><Button variant="ghost" onClick={()=>run(()=>recordEvent('Session revocation requested',user.id,'Demo only. A provider integration is needed to revoke other real sessions.'))}>Request other-session sign out</Button></div></>}
  {section==='recording'&&<><h2>Recording defaults</h2><p className="account-section-description">Starting values for a new recording. You can change metadata before saving.</p><Field label="Preferred input" hint="No hardware is selected or activated here. Input selection requires an explicit capture action."><select value={values.preferredInput} onChange={e=>change('preferredInput',e.target.value)}><option>Ask each time</option><option>Browser default input</option></select></Field><div className="field-row"><Field label="Default recording site"><select value={values.defaultSite} onChange={e=>change('defaultSite',e.target.value)}><option>Anterior chest</option><option>Posterior chest</option><option>Left lateral chest</option><option>Right lateral chest</option><option>Not specified</option></select></Field><Field label="Default position"><select value={values.defaultPosition} onChange={e=>change('defaultPosition',e.target.value)}><option>Seated</option><option>Standing</option><option>Supine</option><option>Not specified</option></select></Field></div><Field label="Preferred sample rate" hint="Preference only. Actual input capabilities must be read from the selected device; an unsupported rate is not guaranteed."><select value={values.sampleRate} onChange={e=>change('sampleRate',Number(e.target.value))}><option value={16000}>16,000 Hz</option><option value={44100}>44,100 Hz</option><option value={48000}>48,000 Hz</option></select></Field><Field label="Playback speed"><select value={values.playbackRate} onChange={e=>change('playbackRate',Number(e.target.value))}><option value={0.75}>0.75×</option><option value={1}>1× · original speed</option><option value={1.25}>1.25×</option></select></Field><Notice>Audio never autoplays. Browser capture and sample plots do not establish clinical sound quality.</Notice></>}
  {section==='data'&&<><h2>Data & storage</h2><p className="account-section-description">Know what this demonstration keeps, and what it does not.</p><StatStrip items={[{label:'Own metadata entries',value:records.length},{label:'Declared audio size',value:bytes(records.reduce((sum,r)=>sum+r.size,0))}]}/><Notice title="No private audio stored">The size shown is fictional metadata, not uploaded server storage. Local persistence contains only demo records, preferences and non-sensitive drafts.</Notice><Field label="Personal retention preference" hint={`System policy presentation is ${state.system.retentionDays} days. This preference creates no automatic deletion job.`}><select value={values.retentionDays} onChange={e=>change('retentionDays',Number(e.target.value))}><option value={30}>30 days</option><option value={90}>90 days</option><option value={180}>180 days</option><option value={365}>365 days</option></select></Field><div className="setting-row"><div><strong>Export personal demonstration metadata</strong><p>Download your fictional profile, own records, runs and preferences as JSON. No audio or secrets.</p></div><Button variant="secondary" onClick={()=>setDialog('export')}><Download size={17}/>Export</Button></div><div className="setting-row"><div><strong>Request account deletion</strong><p>Record a demo request with confirmation. This does not delete an actual identity or server data.</p></div><Button variant="danger" onClick={()=>{setDeleteText('');setDialog('delete');}}>Request deletion</Button></div><p className="note-text section-gap"><Link className="inline-link" to="/privacy">Read the draft privacy notice <ArrowRight size={15}/></Link></p></>}
  <AccountError message={error}/>{section!=='security'&&<SaveBar dirty={dirty} onSave={save} onCancel={()=>setValues(preferences)}/>}
 </section></div>
 <Modal open={!!pendingSection} onClose={()=>setPendingSection('')} title="Keep your preference changes?" footer={<><Button variant="secondary" onClick={()=>setPendingSection('')}>Keep editing</Button><Button variant="ghost" onClick={()=>{setValues(preferences);setParams({section:pendingSection});setPendingSection('');}}>Discard changes</Button><Button onClick={()=>run(()=>{savePreferences(values);setParams({section:pendingSection});setPendingSection('');})}>Save & continue</Button></>}><p>Your changes have not been saved. Save them before opening another Settings section, or discard them.</p></Modal>
 <Modal open={!!dialog} onClose={()=>setDialog(null)} title={dialog==='delete'?'Confirm a demo deletion request':dialog==='export'?'Export your own metadata':dialog==='sessions'?'Sign out this browser':dialog==='reauth'?'Reauthentication required':'Identity linking requires verification'} footer={dialog==='delete'?<><Button variant="secondary" onClick={()=>setDialog(null)}>Cancel</Button><Button variant="danger" disabled={deleteText!=='DELETE'} onClick={()=>run(()=>{recordEvent('Account deletion requested',user.id,'Demo request only. No identity, server data or audio was deleted.');setDialog(null);})}>Record demo request</Button></>:dialog==='export'?<><Button variant="secondary" onClick={()=>setDialog(null)}>Cancel</Button><Button onClick={()=>run(exportMetadata)}>Download JSON</Button></>:dialog==='sessions'?<><Button variant="secondary" onClick={()=>setDialog(null)}>Cancel</Button><Button onClick={()=>{logout();navigate('/login');}}>Sign out</Button></>:<Button variant="secondary" onClick={()=>setDialog(null)}>Understood</Button>}>
  {dialog==='delete'&&<><Notice tone="warning">This is a request preview, not an irreversible deletion. Real identity and storage deletion need a configured authenticated backend.</Notice><Field label="Type DELETE to confirm the demo request"><input autoComplete="off" value={deleteText} onChange={e=>setDeleteText(e.target.value)}/></Field></>}
  {dialog==='export'&&<p>The download includes only <strong>{user.name}’s</strong> fictional metadata. It excludes other accounts, passwords, provider tokens and audio.</p>}
  {dialog==='sessions'&&<p>This ends the selected demo persona session in this browser. Your non-sensitive saved fixtures and preferences remain available when you return.</p>}
  {dialog==='reauth'&&<><Notice title="Authentication integration unavailable">No real provider session exists in this demo. We cannot claim successful reauthentication.</Notice><p>In the connected application, a fresh Firebase credential will be required for email, password and identity-linking changes.</p></>}
  {dialog==='link'&&<><Notice title="No account was linked">Provider linking is not connected. Matching email addresses alone never merges accounts.</Notice><p>The real flow must verify the current identity, handle provider cancellation and resolve existing-account conflicts before linking.</p><Button variant="secondary" to="/auth/callback?state=link-conflict">Preview linking-conflict state</Button></>}
  <AccountError message={error}/>
 </Modal></>;
}

function Notifications(){
 const {state,user,preferences,markNotification,markAllRead}=useApp();const [tab,setTab]=useState('all');const {error,run}=useError();if(!user)return null;
 const all=state.notifications.filter(n=>n.userId===user.id);const rows=all.filter(n=>tab==='all'||!n.read);const unread=all.filter(n=>!n.read).length;
 function authorized(href:string){const path=href.split('?')[0];if(path.startsWith('/app/recordings/'))return canAccess(state,user,path.split('/').pop()||'');if(path.startsWith('/app/results/')){const result=state.results.find(r=>r.id===path.split('/').pop());return !!result&&canAccess(state,user,result.recordingId);}if(path.startsWith('/app/reviews/'))return state.assignments.some(a=>a.id===path.split('/').pop()&&a.analystId===user!.id&&a.permission==='review'&&a.status!=='revoked');return path.startsWith('/app/')&&!path.startsWith('/app/admin');}
 return <><PageHeading eyebrow="Your workspace" title="Notifications" description="Local workflow updates, scoped to your account. No emails or external notifications are sent." actions={<Button variant="secondary" disabled={!unread} onClick={()=>run(markAllRead)}>Mark all as read</Button>}/><Tabs value={tab} onChange={setTab} items={[{id:'all',label:'All updates',count:all.length},{id:'unread',label:'Unread',count:unread}]}/><AccountError message={error}/>{rows.length?<section className="notification-list" aria-label="Your notifications">{rows.map(n=><article className={`notification-item ${n.read?'':'unread'}`} key={n.id}><span className="notification-symbol"><Bell size={21}/></span><div><div className="toolbar"><h2>{n.title}</h2>{!n.read&&<Badge>Unread</Badge>}</div><p>{n.body}</p><time>{formatDate(n.createdAt)}</time><div className="toolbar account-panel-foot">{authorized(n.href)?<Link className="inline-link" to={n.href} onClick={()=>run(()=>markNotification(n.id,true))}>Open workspace <ArrowRight size={15}/></Link>:<span className="note-text">Access is no longer available. Ask the owner for a new share.</span>}<Button variant="ghost" onClick={()=>run(()=>markNotification(n.id,!n.read))}>{n.read?'Mark unread':'Mark read'}</Button></div></div></article>)}</section>:<Empty title={tab==='unread'?'You’re all caught up':'A quiet inbox'} description={tab==='unread'?'There are no unread updates. Saved updates remain in All updates.':'New demo processing and assignment updates will appear here.'}/>}<Notice>Email notifications are {preferences.emailNotifications?'preferred but not configured':'off'}. <Link className="inline-link" to="/app/settings?section=notifications">Manage preferences <ArrowRight size={14}/></Link></Notice></>;
}

function Help(){
 const [search,setSearch]=useState('');const [copied,setCopied]=useState(false);const {user,notify}=useApp();
 const entries=[
  {group:'Recordings',question:'How do I start a recording?',answer:'Choose New recording, then upload a PCM WAV file or open the clearly labelled device-capture demonstration. Use pseudonymous labels and avoid patient-identifying notes. Nothing is uploaded to a private server in this demo.',href:'/app/recordings/new',link:'New recording'},
  {group:'Recordings',question:'Why was my upload rejected?',answer:'Check that the file has a valid WAV header, not simply a .wav filename. Files also need to fit the configured size limit. An unsupported format should be converted by a trusted tool rather than renamed. Remove the file and retry after correcting it.',href:'/app/recordings/new/upload',link:'Open WAV upload'},
  {group:'Recordings',question:'What if my device is denied, missing or silent?',answer:'Recording begins only after an explicit action. Check browser permission, the connected input and the device’s own gain. Do not assume the browser supports a chosen sample rate. The demo can preview denied, disconnected, unsupported, silence and clipping states without pretending hardware is connected.',href:'/app/recordings/new/record',link:'Device workflow'},
  {group:'Processing',question:'Can I leave while an ensemble job runs?',answer:'Yes. Processing has a dedicated workspace and each run keeps its own history. The demo simulates validation, preparation, separation, fusion and saving stages. Elapsed time is not a completion forecast, and no real model inference happens here.',href:'/app/processing',link:'View processing'},
  {group:'Processing',question:'Why is no separation-quality score shown?',answer:'Reference-based measures such as SI-SDR need paired ground-truth sources. Ordinary recordings do not provide these, so the interface says Reference unavailable. Synthetic plots are not measured separation quality and are never a diagnosis.',href:'/app/results',link:'View results'},
  {group:'Access',question:'Who can listen to my recordings?',answer:'You own your recordings. Another account needs an explicit listening share or review assignment. Administrator status alone does not grant audio, waveform or download access. Revoking a share removes the recipient’s current content access.',href:'/app/shared',link:'Manage sharing'},
  {group:'Access',question:'How do analyst reviews work?',answer:'An owner explicitly assigns a recording to an active analyst. The analyst can save timestamped non-diagnostic notes, mark the review complete or request re-recording. Unassigned private recordings remain unavailable.',href:user?.role==='analyst'?'/app/review-queue':'/app/shared',link:user?.role==='analyst'?'Review queue':'Shared recordings'},
  {group:'Account',question:'I forgot my password or my reset link expired.',answer:'Use password recovery to request another link. In this demonstration, no email is sent. A real provider must validate link expiry and one-time use; reset action codes should never be copied into support reports.',href:'/forgot-password',link:'Password recovery'},
  {group:'Account',question:'Can Google and password identities be combined?',answer:'Only through a configured provider-linking flow with reauthentication. Equal email strings are not enough to prove identity. Linking, cancellation and conflict screens are shown honestly while the provider is not connected.',href:'/app/settings?section=security',link:'Security settings'},
  {group:'Accessibility',question:'Can I turn off the owl animation and snow?',answer:'Yes. Enable reduced motion in Appearance, or use your system’s reduced-motion setting. Core workflows do not depend on animation. You can also increase interface contrast without changing the approved winter theme.',href:'/app/settings?section=appearance',link:'Appearance settings'},
 ];
 const visible=entries.filter(e=>`${e.question} ${e.answer} ${e.group}`.toLowerCase().includes(search.toLowerCase()));
 return <><PageHeading eyebrow="Guidance & support" title="A little clarity, when you need it." description="Practical guidance for recording, reviewing and managing your research workspace."/><Field className="help-search" label="Search help"><input type="search" placeholder="Try sharing, WAV, password or motion…" value={search} onChange={e=>setSearch(e.target.value)}/></Field><div className="help-grid account-help-grid"><Panel className="account-help-guides" title="Workspace guides" actions={<Badge>{visible.length} {visible.length===1?'guide':'guides'}</Badge>}>{visible.length?visible.map(e=><details key={e.question}><summary>{e.question}</summary><Badge>{e.group}</Badge><p>{e.answer}</p><Link className="inline-link" to={e.href}>{e.link}<ArrowRight size={15}/></Link></details>):<Empty title="No matching guide" description="Try a shorter phrase, such as device, access or password." action={<Button variant="secondary" onClick={()=>setSearch('')}>Clear search</Button>}/>}</Panel><aside><Panel title="Before sharing a support report" description="Keep personal and credential information out of your message."><ol className="help-checklist"><li>Describe the screen and action that failed.</li><li>Include a fictional recording or job ID, if useful.</li><li>Do not include passwords, reset URLs, authentication tokens or patient recordings.</li><li>State that the problem occurred in demonstration mode.</li></ol><Button variant="secondary" onClick={async()=>{try{await navigator.clipboard.writeText(`StethoFuse frontend demonstration\nScreen: ${window.location.pathname}\nIssue: [describe the action and observed behavior]\nExpected: [describe expected result]\nNo passwords, reset links, tokens or private audio attached.`);setCopied(true);notify('Safe support template copied.');}catch{notify('Clipboard is unavailable. Use the checklist to write a report.');}}}>{copied?<CheckCircle size={18}/>:<IdentificationCard size={18}/>} {copied?'Template copied':'Copy safe report template'}</Button><p className="note-text section-gap">Support delivery is not configured. Copying this template does not send a ticket or email.</p><WinterNote>A little context makes the next step clearer.</WinterNote></Panel><Notice title="Research, not diagnosis">{brand.researchNotice} Do not use demonstration outputs as medical advice or as evidence of clinical accuracy.</Notice><div className="toolbar"><Link className="inline-link" to="/privacy">Draft privacy notice</Link><Link className="inline-link" to="/terms">Draft terms</Link></div></aside></div></>;
}
