import {useCallback,useEffect,useRef,useState,type FormEvent} from 'react';
import {Link,Navigate,useLocation,useNavigate,useSearchParams} from 'react-router-dom';
import {ArrowRight,Plus,UploadSimple} from '@phosphor-icons/react';
import Shell from '../components/Shell';
import {Badge,Button,CopyId,Empty,ErrorState,Field,Notice,PageHeading,Panel,Skeleton,StatStrip,Status,Table,UnsavedGuard} from '../components/ui';
import {useLive} from '../data/live';
import {useApp} from '../data/store';
import {liveRoleLabel,type LiveAudit,type LiveGrant,type LiveJob,type LivePreferences,type LiveRecording,type LiveResult,type LiveReview,type LiveRole,type LiveStatus,type LiveUser,type MediaResource} from '../data/liveTypes';
import {ApiError} from '../data/api';
import {liveAuth,authErrorMessage} from '../auth/firebase';
import './workspace-pages.css';
import './account-pages.css';

const date=(seconds:number|null)=>seconds?new Date(seconds*1000).toLocaleString():'Not saved';
const message=(error:unknown)=>error instanceof Error?error.message:'The operation could not be completed.';
function useRemote<T>(path:string){
 const {api}=useLive();const [value,setValue]=useState<T|null>(null),[error,setError]=useState(''),[loading,setLoading]=useState(true),[version,setVersion]=useState(0);
 useEffect(()=>{const controller=new AbortController();setValue(null);setLoading(true);setError('');
  void api.json<T>(path,{signal:controller.signal}).then(data=>{if(!controller.signal.aborted)setValue(data);}).catch(failure=>{if(!controller.signal.aborted)setError(message(failure));}).finally(()=>{if(!controller.signal.aborted)setLoading(false);});
  return()=>controller.abort();
 },[api,path,version]);
 return {value,error,loading,reload:()=>setVersion(v=>v+1)};
}
function RequestState({loading,error,reload}:{loading:boolean;error:string;reload:()=>void}){return loading?<Skeleton/>:error?<ErrorState message={error} onRetry={reload}/>:null;}
function Unavailable({title,detail}:{title:string;detail:string}){return <><PageHeading title={title} description="Live workspace"/><Notice title="Not connected in this milestone"><p>{detail}</p><p>No fictional values or simulated completion are substituted.</p></Notice><Button to="/app/dashboard" variant="secondary">Back to workspace</Button></>;}

function ProtectedMedia({resources}:{resources:MediaResource[]}){
 const {api}=useLive();const [urls,setUrls]=useState<Record<string,string>>({}),[types,setTypes]=useState<Record<string,string>>({}),[error,setError]=useState(''),[busy,setBusy]=useState<string|null>(null);
 const allocated=useRef(new Map<string,string>()),active=useRef(true),requests=useRef(new Set<AbortController>());
 useEffect(()=>{active.current=true;return()=>{active.current=false;for(const controller of requests.current)controller.abort();for(const url of allocated.current.values())URL.revokeObjectURL(url);allocated.current.clear();};},[api]);
 async function load(resource:MediaResource){
  const controller=new AbortController();requests.current.add(controller);setBusy(resource.id);setError('');
  try{const blob=await api.media(resource.id,controller.signal);if(!active.current||controller.signal.aborted)return;const url=URL.createObjectURL(blob),old=allocated.current.get(resource.id);if(old)URL.revokeObjectURL(old);allocated.current.set(resource.id,url);setUrls(values=>({...values,[resource.id]:url}));setTypes(values=>({...values,[resource.id]:blob.type}));}
  catch(failure){if(active.current&&!controller.signal.aborted){setError(message(failure));const old=allocated.current.get(resource.id);if(old)URL.revokeObjectURL(old);allocated.current.delete(resource.id);setUrls(values=>{const next={...values};delete next[resource.id];return next;});}}
  finally{requests.current.delete(controller);if(active.current)setBusy(null);}
 }
 if(!resources.length)return <Notice>No media is included in your current grant. Sibling files are not automatically shared.</Notice>;
 return <Panel title="Authorized media" description="Files are fetched with your current identity. No public media URL or query token is used.">{error&&<ErrorState message={error}/>}<div className="audio-tracks">{resources.map(resource=><section className="audio-track" key={resource.id}><h3>{resource.kind.replaceAll('_',' ')}</h3>{urls[resource.id]?(types[resource.id]?.startsWith('audio/')?<audio controls preload="metadata" src={urls[resource.id]}/>:types[resource.id]?.startsWith('image/')?<img src={urls[resource.id]} alt={`${resource.kind.replaceAll('_',' ')} for this authorized recording`}/>:null):null}<div className="toolbar"><Button variant="secondary" disabled={!!busy} onClick={()=>void load(resource)}>{busy===resource.id?'Loading…':urls[resource.id]?'Recheck access and reload':'Load authorized file'}</Button>{urls[resource.id]&&<a className="inline-link" href={urls[resource.id]} download={`${resource.kind}.${({'audio/wav':'wav','audio/x-wav':'wav','audio/wave':'wav','audio/mpeg':'mp3','audio/ogg':'ogg','image/png':'png','image/webp':'webp','image/jpeg':'jpg'} as Record<string,string>)[types[resource.id]]||'bin'}`}>Download loaded file</a>}</div></section>)}</div><p className="note-text">Revocation blocks future requests, but cannot recall bytes already downloaded. Leave this page or sign out to release loaded files.</p></Panel>;
}
function Dashboard(){
 const {session}=useLive();const records=useRemote<{items:LiveRecording[]}>('/recordings'),jobs=useRemote<{items:LiveJob[]}>('/jobs'),results=useRemote<{items:LiveResult[]}>('/results');
 const own=records.value?.items.filter(r=>r.is_owner)||[];
 return <><PageHeading eyebrow="Your research workspace" title={`A clear place to listen, ${session!.user.display_name||'researcher'}.`} description="Your account, recordings and authorized research work." actions={<Button to="/app/recordings/new"><Plus size={18}/>New recording</Button>}/><StatStrip items={[{label:'Own recordings',value:records.loading?'…':records.error?'Unavailable':own.length},{label:'Saved jobs',value:jobs.loading?'…':jobs.error?'Unavailable':jobs.value?.items.length??0},{label:'Authorized results',value:results.loading?'…':results.error?'Unavailable':results.value?.items.length??0}]}/><div className="dashboard-grid"><Panel title="Recent recordings"><RequestState {...records}/>{!records.loading&&!records.error&&(own.length?own.slice(0,5).map(r=><Link className="list-row" to={`/app/recordings/${r.id}`} key={r.id}><div><strong>{r.title}</strong><p>{date(r.created_at)}</p></div><ArrowRight size={18}/></Link>):<Empty artKind="dashboardCollection" title="Begin your own collection" description="Upload a non-sensitive research WAV file. Other accounts’ private recordings are not included." action={<Button to="/app/recordings/new/upload">Add a recording</Button>}/>)}</Panel><Panel title="One recording. Distinct components."><p>Keep authorized original recordings and their real processing history together.</p><Notice title="Ensemble execution is not connected">This milestone does not manufacture jobs, separated signals, waveforms or quality scores.</Notice><Button to="/app/shared" variant="secondary">Shared & assigned</Button></Panel></div>{jobs.error&&<ErrorState message={jobs.error}/>} {results.error&&<ErrorState message={results.error}/>}</>;
}
function Recordings({shared=false}:{shared?:boolean}){
 const data=useRemote<{items:LiveRecording[]}>('/recordings');const [search,setSearch]=useState('');
 const rows=(data.value?.items||[]).filter(r=>(shared?!r.is_owner:r.is_owner)&&`${r.title} ${r.id}`.toLowerCase().includes(search.toLowerCase()));
 return <><PageHeading title={shared?'Shared & assigned':'My recordings'} description={shared?'Only recordings currently authorized by explicit grants.':'Your persisted recordings; ownership is resolved by the backend.'} actions={!shared&&<Button to="/app/recordings/new"><Plus size={18}/>New recording</Button>}/><div className="toolbar"><Field label="Search recordings"><input type="search" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Title or recording ID"/></Field><Button variant="secondary" onClick={data.reload}>Refresh access</Button></div><RequestState {...data}/>{!data.loading&&!data.error&&(rows.length?<Table headers={['Recording','Created','Format','Access','']} caption="Authorized recordings">{rows.map(r=><tr key={r.id}><td><strong>{r.title}</strong><p><CopyId value={r.id}/></p></td><td>{date(r.created_at)}</td><td>{r.sample_rate_hz} Hz · {r.channels} ch</td><td><Badge>{r.is_owner?'Owner':'Explicit grant'}</Badge></td><td><Link className="inline-link" to={`/app/recordings/${r.id}`}>Open <ArrowRight size={16}/></Link></td></tr>)}</Table>:<Empty title={shared?'No shared recordings':'Your collection is ready'} description={shared?'Ask an owner to grant your application user ID access. An admin role is not an audio grant.':'Upload a WAV file to begin. No demonstration recordings are loaded.'}/>)}{shared&&<Notice>Owners manage grants from an owned recording. Revoking one grant does not remove access from other grants.</Notice>}</>;
}
function NewRecording(){return <><PageHeading title="Start with a recording" description="Choose a supported live input path."/><div className="capture-options"><Panel title="Upload a WAV file"><p>Mono or stereo PCM WAV, up to 25 MiB. The server validates the file and assigns ownership from your identity.</p><Button to="/app/recordings/new/upload"><UploadSimple size={18}/>Upload WAV</Button></Panel><Panel title="Connected device"><p>Live microphone/device capture is not connected in M1. No simulated capture is shown in live mode.</p><Button disabled>Device capture unavailable</Button></Panel></div></>;}
function Upload(){
 const {api}=useLive(),navigate=useNavigate();const [file,setFile]=useState<File|null>(null),[title,setTitle]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');
 async function submit(e:FormEvent){e.preventDefault();setError('');if(!file){setError('Choose a WAV file.');return;}if(file.size>25*1024*1024||!file.name.toLowerCase().endsWith('.wav')){setError('Choose a WAV file no larger than 25 MiB.');return;}setBusy(true);try{const body=new FormData();body.set('file',file);if(title.trim())body.set('title',title.trim());const record=await api.json<LiveRecording>('/recordings',{method:'POST',body});navigate(`/app/recordings/${record.id}`);}catch(failure){setError(message(failure));}finally{setBusy(false);}}
 return <><PageHeading title="Upload a recording" description="Only use non-sensitive audio you are authorized to use for research."/><Panel><form onSubmit={submit}><Field label="WAV file" hint="Mono/stereo PCM WAV · maximum 25 MiB"><input type="file" accept=".wav,audio/wav" disabled={busy} onChange={e=>setFile(e.target.files?.[0]||null)}/></Field><Field label="Recording title"><input maxLength={200} value={title} onChange={e=>setTitle(e.target.value)} placeholder="Pseudonymous research label"/></Field>{error&&<ErrorState message={error}/>}<div className="toolbar"><Button type="submit" disabled={busy}>{busy?'Uploading…':'Upload recording'}</Button><Button to="/app/recordings" variant="secondary">Cancel</Button></div><Notice>No client owner ID or role is submitted. The application creates no record until the server accepts the upload.</Notice></form></Panel></>;
}
function Grants({record}:{record:LiveRecording}){
 const {api}=useLive();const data=useRemote<{items:LiveGrant[]}>(`/recordings/${record.id}/grants`);const [recipient,setRecipient]=useState(''),[permission,setPermission]=useState<'read'|'review'>('read'),[resource,setResource]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');
 async function run(action:()=>Promise<unknown>){setBusy(true);setError('');try{await action();data.reload();}catch(failure){setError(message(failure));}finally{setBusy(false);}}
 const selectable=record.resources.filter(r=>permission==='read'||['original_audio','result'].includes(r.kind));
 return <Panel title="Explicit sharing" description="Use the recipient's application user ID supplied out of band. There is no public user directory."><form onSubmit={e=>{e.preventDefault();void run(()=>api.json(`/recordings/${record.id}/grants`,{method:'POST',body:JSON.stringify({recipient_id:recipient.trim(),permission,...(resource?{resource_id:resource}:{})})}));}}><div className="form-grid"><Field label="Recipient application ID"><input required value={recipient} onChange={e=>setRecipient(e.target.value)} autoComplete="off"/></Field><Field label="Permission"><select value={permission} onChange={e=>{setPermission(e.target.value as 'read'|'review');setResource('');}}><option value="read">Listen/read</option><option value="review">Analyst review</option></select></Field><Field label="Resource scope"><select value={resource} onChange={e=>setResource(e.target.value)} required={permission==='review'}><option value="">{permission==='review'?'Choose an exact original or result':'Whole recording (all authorized resources)'}</option>{selectable.map(r=><option key={r.id} value={r.id}>{r.kind.replaceAll('_',' ')} · {r.id}</option>)}</select></Field></div><Button type="submit" disabled={busy}>{busy?'Saving…':'Grant access'}</Button></form>{error&&<ErrorState message={error}/>}<RequestState {...data}/>{data.value&&<Table headers={['Recipient','Permission / scope','Status','Actions']} caption="Recording grants">{data.value.items.map(grant=><tr key={grant.id}><td><CopyId value={grant.recipient_id}/></td><td>{grant.permission}<p>{grant.resource_id||'Whole recording'}</p></td><td><Status value={grant.status}/></td><td><Button variant="danger" disabled={busy||grant.status==='revoked'} onClick={()=>{if(window.confirm('Revoke this grant only? Other active grants may still authorize access.'))void run(()=>api.json(`/grants/${grant.id}`,{method:'DELETE'}));}}>Revoke grant</Button><Button variant="ghost" disabled={busy||grant.status==='revoked'} onClick={()=>{if(window.confirm('Revoke ALL this recipient’s grants on this recording? Already downloaded files cannot be recalled.'))void run(()=>api.json(`/recordings/${record.id}/revoke-access`,{method:'POST',body:JSON.stringify({recipient_id:grant.recipient_id,confirmed_recording_id:record.id})}));}}>Revoke all access</Button></td></tr>)}</Table>}<Notice>Review requires a current analyst and one exact original-audio or result resource. Replacement grants receive new IDs; previous notes are not transferred.</Notice></Panel>;
}
function RecordingDetail({id}:{id:string}){
 const {api,session}=useLive();const data=useRemote<LiveRecording>(`/recordings/${id}`);const [title,setTitle]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 useEffect(()=>{setTitle(data.value?.title||'');},[data.value]);
 async function rename(e:FormEvent){e.preventDefault();setBusy(true);setError('');try{await api.json(`/recordings/${id}`,{method:'PATCH',body:JSON.stringify({title:title.trim()})});data.reload();}catch(failure){setError(message(failure));}finally{setBusy(false);}}
 const record=data.value;
 return <><PageHeading title={record?.title||'Recording'} description="Private recording details are returned only after a current backend access check."/><RequestState {...data}/>{record&&<><StatStrip items={[{label:'Recording ID',value:<CopyId value={record.id}/>},{label:'Duration',value:`${record.duration_sec.toFixed(1)} s`},{label:'Sample rate',value:`${record.sample_rate_hz} Hz`},{label:'Access',value:record.is_owner?'Owner':'Explicit grant'}]}/><ProtectedMedia key={record.id} resources={record.resources}/>{record.is_owner&&<><Panel title="Owned recording"><form onSubmit={rename}><Field label="Recording title"><input required maxLength={200} value={title} onChange={e=>setTitle(e.target.value)}/></Field><Button type="submit" disabled={busy||title.trim()===record.title}>{busy?'Saving…':'Save title'}</Button></form>{error&&<ErrorState message={error}/>}<div className="toolbar"><Button disabled={!session?.capabilities.ensemble||busy} onClick={async()=>{setBusy(true);setError('');try{await api.json(`/recordings/${id}/jobs`,{method:'POST',body:'{}'});}catch(failure){setError(message(failure));}finally{setBusy(false);}}}>Request ensemble processing</Button><Button disabled variant="danger">Deletion not connected</Button></div><Notice>Ensemble execution, metadata fields beyond title, archive and deletion are not connected in M1. No model run or destructive completion is simulated.</Notice></Panel><Grants record={record}/></>}</>}</>;
}
function Jobs({id}:{id?:string}){
 const data=useRemote<{items:LiveJob[]}|LiveJob>(id?`/jobs/${id}`:'/jobs');const rows=data.value?('items'in data.value?data.value.items:[data.value]):[];
 return <><PageHeading title={id?'Processing run':'Processing history'} description="Only persisted owner-scoped jobs. No simulated progress is generated."/><RequestState {...data}/>{!data.loading&&!data.error&&(rows.length?<Table headers={['Job','Recording','Status','Created']} caption="Real processing history">{rows.map(job=><tr key={job.id}><td><Link to={`/app/processing/${job.id}`}>{job.id}</Link></td><td><Link to={`/app/recordings/${job.recording_id}`}>{job.recording_id}</Link></td><td><Status value={job.status}/>{job.error_code&&<p>Processing did not complete.</p>}</td><td>{date(job.created_at)}</td></tr>)}</Table>:<Empty title="No processing runs" description="Ensemble execution is not connected. Your uploaded originals remain available."/>)}<Notice>Cancellation, retry and internal expert selection are not enabled here. Normal users will request one ensemble workflow when its executor is connected.</Notice></>;
}
function Results({id}:{id?:string}){
 const data=useRemote<{items:LiveResult[]}|LiveResult>(id?`/results/${id}`:'/results');const rows=data.value?('items'in data.value?data.value.items:[data.value]):[];
 return <><PageHeading title={id?'Separation result':'Results'} description="Persisted outputs and provenance only; no synthetic audio or invented scores."/><RequestState {...data}/>{!data.loading&&!data.error&&(rows.length?rows.map(result=><Panel key={result.id} title={result.method_label||'Saved result'} description={date(result.created_at)}><p><CopyId value={result.id}/></p><Link className="inline-link" to={`/app/recordings/${result.recording_id}`}>Original recording <ArrowRight size={16}/></Link>{id?<ProtectedMedia resources={result.resources}/>:<Button to={`/app/results/${result.id}`} variant="secondary">Open result</Button>}</Panel>):<Empty title="No saved results" description="Outputs appear only after real authorized results have been persisted. Ensemble processing is not connected yet."/>)}</>;
}
function Assignments(){
 const data=useRemote<{items:LiveGrant[]}>('/assignments');
 return <><PageHeading title="Review queue" description="Your active exact-resource analyst assignments." actions={<Button variant="secondary" onClick={data.reload}>Refresh access</Button>}/><RequestState {...data}/>{!data.loading&&!data.error&&(data.value?.items.length?<Table headers={['Assignment','Recording','Resource','Created','']} caption="Analyst assignments">{data.value.items.map(grant=><tr key={grant.id}><td><CopyId value={grant.id}/></td><td>{grant.recording_id}</td><td>{grant.resource_id}</td><td>{date(grant.created_at)}</td><td><Link className="inline-link" to={`/app/reviews/${grant.id}`}>Review <ArrowRight size={16}/></Link></td></tr>)}</Table>:<Empty title="No active assignments" description="An owner must grant review access to your application ID for one original-audio or result resource."/>)}</>;
}
function Review({id}:{id:string}){
 const {api}=useLive();const data=useRemote<LiveReview>(`/assignments/${id}/review`);const [notes,setNotes]=useState(''),[decision,setDecision]=useState<LiveReview['decision']>('pending'),[error,setError]=useState(''),[busy,setBusy]=useState(false),[saved,setSaved]=useState(false);
 useEffect(()=>{if(data.value){setNotes(data.value.notes);setDecision(data.value.decision);}},[data.value]);
 const dirty=!!data.value&&(notes!==data.value.notes||decision!==data.value.decision);
 async function save(e:FormEvent){e.preventDefault();setBusy(true);setError('');setSaved(false);try{await api.json(`/assignments/${id}/review`,{method:'PUT',body:JSON.stringify({decision,notes})});setSaved(true);data.reload();}catch(failure){setError(message(failure));}finally{setBusy(false);}}
 return <><PageHeading title="Assigned review" description="A non-diagnostic review of the exact assigned resource."/><RequestState {...data}/>{data.value&&<><ProtectedMedia resources={[{id:data.value.resource_id,kind:'assigned_resource',media_type:null,url:null}]}/><Panel title="Review notes"><form onSubmit={save}><Field label="Review decision"><select value={decision} onChange={e=>setDecision(e.target.value as LiveReview['decision'])}><option value="pending">Pending</option><option value="accepted">Reviewed</option><option value="needs_attention">Needs attention / re-record</option></select></Field><Field label="Non-diagnostic notes" hint="Do not include patient identifiers. Maximum 10,000 characters."><textarea rows={7} maxLength={10000} value={notes} onChange={e=>setNotes(e.target.value)}/></Field>{error&&<ErrorState message={error}/>} {saved&&<p role="status">Review saved by the server.</p>}<Button type="submit" disabled={busy||!dirty}>{busy?'Saving…':'Save review'}</Button></form></Panel><UnsavedGuard when={dirty&&!busy}/></>}</>;
}

function Profile(){
 const {session,api,refreshAccount}=useLive();const user=session!.user;const [name,setName]=useState(user.display_name),[busy,setBusy]=useState(false),[error,setError]=useState(''),[saved,setSaved]=useState(false);
 async function save(e:FormEvent){e.preventDefault();setBusy(true);setError('');try{await api.json('/auth/me',{method:'PATCH',body:JSON.stringify({display_name:name.trim()})});await refreshAccount();setSaved(true);}catch(failure){setError(message(failure));}finally{setBusy(false);}}
 return <><PageHeading title="Your profile" description="Application profile and server-assigned access."/><Panel><p>Application ID: <CopyId value={user.id}/></p><p>Email: {user.email}</p><p>Role: {liveRoleLabel(user.role)}</p><p>Status: <Status value={user.status}/></p><form onSubmit={save}><Field label="Display name"><input required maxLength={200} value={name} onChange={e=>setName(e.target.value)}/></Field>{error&&<ErrorState message={error}/>} {saved&&<p role="status">Profile saved.</p>}<Button type="submit" disabled={busy||name.trim()===user.display_name}>Save changes</Button></form></Panel><UnsavedGuard when={!busy&&name.trim()!==user.display_name}/></>;
}
function Settings(){
 const {preferences,savePreferences,session,logout}=useLive();const [params]=useSearchParams();const section=params.get('section')||'general';const {notify}=useApp();
 const [busy,setBusy]=useState(false),[error,setError]=useState('');const appearance=preferences.appearance||{};
 async function save(value:LivePreferences){setBusy(true);setError('');try{await savePreferences(value);notify('Preferences saved by the server.');}catch(failure){setError(message(failure));}finally{setBusy(false);}}
 return <><PageHeading title="Personal settings" description="Live account settings. Unconnected operations remain unavailable."/><nav className="tabs" aria-label="Settings sections">{['general','appearance','notifications','security','recording','data'].map(s=><Link key={s} className={s===section?'active':''} to={`/app/settings?section=${s}`}>{s[0].toUpperCase()+s.slice(1)}</Link>)}</nav>{error&&<ErrorState message={error}/>}<Panel title={section==='appearance'?'Appearance':section==='security'?'Account security':'Account preferences'}>{section==='appearance'?<>{(['reducedMotion','snow','highContrast'] as const).map(key=><label className="setting-toggle" key={key}><span>{({reducedMotion:'Reduced motion',snow:'Snow',highContrast:'Higher contrast'})[key]}</span><input type="checkbox" disabled={busy} checked={appearance[key]===true||(key==='snow'&&appearance[key]!==false)} onChange={e=>void save({appearance:{...appearance,[key]:e.target.checked}})}/></label>)}</>:section==='security'?<><p>Firebase manages identity and browser-session persistence. This app never stores a separate password database.</p><Button variant="secondary" disabled={busy} onClick={async()=>{setBusy(true);setError('');try{await liveAuth.requestReset(session!.user.email);notify('Firebase accepted the recovery request. Check your inbox if eligible.');}catch(failure){setError(authErrorMessage(failure));}finally{setBusy(false);}}}>Request password reset</Button><Button variant="ghost" onClick={()=>void logout()}>Sign out of this session</Button><Notice>Provider linking and other device sessions require a separately connected reauthentication flow. They are not simulated.</Notice></>:section==='general'?<><p>Display name and application ID are available in your profile.</p><Button to="/app/profile" variant="secondary">Your profile</Button><Notice>General display preferences beyond appearance are not exposed by this M1 screen yet.</Notice></>:<Notice>{section==='notifications'?'Email and workflow notification delivery is not connected.':section==='recording'?'Live device-capture defaults are not connected. Upload validates actual file properties on the server.':'Account export, deletion and retention operations are not connected. No deletion or export completion is simulated.'}</Notice>}</Panel></>;
}
function AdminUsers(){
 const {api,refreshAccount}=useLive();const data=useRemote<{items:LiveUser[]}>('/admin/users');const [search,setSearch]=useState('');
 return <><PageHeading title="Users" description="Backend-authorized account metadata; private recordings are not included."/><Field label="Search users"><input type="search" value={search} onChange={e=>setSearch(e.target.value)}/></Field><RequestState {...data}/>{data.value&&<Table headers={['User / application ID','Email','Role','Status','Action']} caption="Application users">{data.value.items.filter(u=>`${u.id} ${u.email} ${u.display_name}`.toLowerCase().includes(search.toLowerCase())).map(user=><AdminUserRow key={`${user.id}:${user.role}:${user.status}`} user={user} save={async(role,status)=>{await api.json(`/admin/users/${user.id}`,{method:'PATCH',body:JSON.stringify({role,status,confirmed_target_id:user.id})});await refreshAccount();data.reload();}}/>)}</Table>}</>;
}
function AdminUserRow({user,save}:{user:LiveUser;save:(role:LiveRole,status:LiveStatus)=>Promise<void>}){
 const [role,setRole]=useState(user.role),[status,setStatus]=useState(user.status),[busy,setBusy]=useState(false),[error,setError]=useState('');
 return <tr><td><strong>{user.display_name||'Research user'}</strong><p><CopyId value={user.id}/></p></td><td>{user.email}</td><td><select aria-label={`Role for ${user.id}`} value={role} onChange={e=>setRole(e.target.value as LiveRole)}><option value="healthcare_staff">Healthcare Staff</option><option value="audio_analyst">Audio Analyst</option><option value="admin">Administrator</option></select></td><td><select aria-label={`Status for ${user.id}`} value={status} onChange={e=>setStatus(e.target.value as LiveStatus)}><option value="active">Active</option><option value="suspended">Suspended</option><option value="disabled">Disabled</option></select></td><td><Button disabled={busy||(role===user.role&&status===user.status)} onClick={async()=>{if(!window.confirm(`Change ${user.id} to ${role} / ${status}? This changes server-enforced access.`))return;setBusy(true);setError('');try{await save(role,status);}catch(failure){setError(message(failure));}finally{setBusy(false);}}}>{busy?'Saving…':'Confirm changes'}</Button>{error&&<p role="alert">{error}</p>}</td></tr>;
}
function AdminAudit(){const data=useRemote<{items:LiveAudit[]}>('/admin/audit');return <><PageHeading title="Audit log" description="Safe operational event metadata, without tokens or private review content."/><RequestState {...data}/>{data.value&&<Table headers={['Time','Actor','Action','Target']} caption="Operational audit">{data.value.items.map(event=><tr key={event.id}><td>{date(event.created_at)}</td><td>{event.actor_id}</td><td>{event.action}</td><td>{event.target_id}</td></tr>)}</Table>}</>;}
function AdminOverview(){const data=useRemote<{items:LiveUser[]}>('/admin/users');return <><PageHeading title="Administration overview" description="Operational metadata is separate from private audio access."/><RequestState {...data}/>{data.value&&<StatStrip items={[{label:'Application accounts',value:data.value.items.length},{label:'Active accounts',value:data.value.items.filter(u=>u.status==='active').length},{label:'Administrators',value:data.value.items.filter(u=>u.role==='admin').length}]}/>}<Panel title="Account administration"><div className="toolbar"><Button to="/app/admin/users">Manage users</Button><Button to="/app/admin/audit" variant="secondary">Audit log</Button></div><Notice>Private media still requires ownership or an explicit grant. No email address or browser role picker can bootstrap an administrator.</Notice></Panel></>;}
function LiveRoute(){
 const {pathname}=useLocation();
 if(pathname==='/app/dashboard')return <Dashboard/>;
 if(pathname==='/app/recordings')return <Recordings/>;
 if(pathname==='/app/shared')return <Recordings shared/>;
 if(pathname==='/app/recordings/new')return <NewRecording/>;
 if(pathname==='/app/recordings/new/upload')return <Upload/>;
 if(pathname==='/app/recordings/new/record')return <Unavailable title="Device recording" detail="Live hardware capture is not connected. Upload an authorized research WAV instead."/>;
 if(/^\/app\/recordings\/[^/]+$/.test(pathname))return <RecordingDetail id={pathname.split('/')[3]}/>;
 if(['/app/processing','/app/history'].includes(pathname))return <Jobs/>;
 if(/^\/app\/processing\/[^/]+$/.test(pathname))return <Jobs id={pathname.split('/')[3]}/>;
 if(pathname==='/app/results')return <Results/>;
 if(/^\/app\/results\/[^/]+$/.test(pathname))return <Results id={pathname.split('/')[3]}/>;
 if(['/app/review-queue','/app/assigned'].includes(pathname))return <Assignments/>;
 if(pathname==='/app/review-history')return <Unavailable title="Review history" detail="The current API exposes active assignments. Historical review retrieval is not connected to this screen yet; old notes are retained by the backend."/>;
 if(/^\/app\/reviews\/[^/]+$/.test(pathname))return <Review id={pathname.split('/')[3]}/>;
 if(pathname==='/app/profile')return <Profile/>;
 if(pathname==='/app/settings')return <Settings/>;
 if(pathname==='/app/admin')return <AdminOverview/>;
 if(pathname==='/app/admin/users')return <AdminUsers/>;
 if(pathname==='/app/admin/audit')return <AdminAudit/>;
 if(pathname==='/app/help')return <><PageHeading title="Help & guidance" description="Live research workspace"/><Panel title="Recording access"><p>Upload a non-sensitive PCM WAV. Your backend account owns the recording. Give another existing account an explicit read or exact-resource review grant from the recording page.</p><p>Use Revoke grant to remove one permission, or Revoke all access to remove all this recipient’s grants on a recording. Already downloaded files cannot be recalled.</p><p>Ensemble execution, device capture and notification delivery are not connected. Contact the project owner without sharing passwords, tokens, recovery links or private audio.</p></Panel></>;
 return <Unavailable title={pathname.startsWith('/app/admin')?'Administrative feature unavailable':'Workspace feature unavailable'} detail="This screen has no connected M1 API yet. It cannot mutate local demo data in live mode."/>;
}
export default function LiveWorkspacePages(){
 const {status,error,session,refreshAccount,logout}=useLive(),location=useLocation();
 if(status==='loading')return <div className="workspace"><Skeleton/></div>;
 if(status==='expired')return <Navigate replace to={`/session-expired?returnTo=${encodeURIComponent(location.pathname)}`}/>;
 if(status==='unverified')return <Navigate replace to="/verify-email"/>;
 if(status==='disabled')return <Navigate replace to="/account-disabled"/>;
 if(status==='signed-out')return <Navigate replace to={`/login?returnTo=${encodeURIComponent(location.pathname)}`}/>;
 if(status==='error'||!session)return <div className="utility-screen"><div className="utility-inner"><h1>Workspace unavailable.</h1><ErrorState message={error||'Account services are unavailable.'} onRetry={()=>void refreshAccount()}/><div className="toolbar"><Button to="/login" variant="secondary">Back to sign in</Button><Button variant="ghost" onClick={()=>void logout()}>Sign out</Button></div></div></div>;
 const path=location.pathname,role=session.user.role;
 if((path.startsWith('/app/admin')&&role!=='admin')||(/^\/app\/(review-queue|assigned|reviews|review-history)(\/|$)/.test(path)&&role!=='audio_analyst'))return <Navigate replace to="/403"/>;
 return <Shell key={session.user.id}><div className="workspace-page" data-live-workspace="true"><LiveRoute key={path}/></div></Shell>;
}
